### ISSUE TITLE
Infrastructure Contexts

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#101]
Internal to Netflix we have a concept of Contexts, tied to a request that gets passed across service calls. These contexts are majorly targeted towards "infrastructure concerns" like tracing information which is hidden from a "developer next door"!

Since, propagation of these contexts requires participation from both client and server, it is imperative that the same is in a place which can be used by both ends of the IPC stack. Hence, this proposal of adding this functionality to RxNetty.
### Features
- _Opt-in_: This feature would be completely opt-in from RxNetty's standpoint and will be in a different module. Karyon & Ribbon which are built on top of RxNetty, however will support this by default.
- _Non-intrusive_: This will be completely driven by netty's ChannelHandler, i.e. even if the binary is in the classpath. A user has to explicitly choose to add this handler into the pipeline if they want to use this feature.
- _Multi-protocol_: This feature should be pluggable into any wire-protocol. The pluggability would be around "how to read-write this context from the wire". Apart from the wire-level protocol handling, everything else would be identical for all protocols.
- _Serialization_: How to serialize-de-serialize these contexts over the wire would be extensible, even for the same protocol. eg: I can serialize the context into a json, custom string, binary data, etc.
### Out of scope
- After these contexts get into the application layer i.e. in most cases after the completion of netty's pipeline, it is upto the application to manage these contexts across threads. So, RxNetty will not provide ways to copy this data from one thread to another during the execution of the request.
### Practical usage
- Although, one can do enough work to use this facility directly from RxNetty, it will be much easier if used via [karyon](https://github.com/Netflix/karyon) and [ribbon](https://github.com/Netflix/ribbon)

**Comment by benjchristensen** [comment]
Hystrix also needs this type of behavior for certain functionalities: https://github.com/Netflix/Hystrix/wiki/How-To-Use#RequestContextSetup

**Comment by benjchristensen** [comment]
> Serialization

I don't think there should be automatic serialization. Anything and everything can and will end up in these contexts and most should not ever leave the context (the Hystrix stuff for example).

**Comment by NiteshKant** [comment]
> > > I don't think there should be automatic serialization. Anything and everything can and will end up in these contexts and most should not ever leave the context (the Hystrix stuff for example).

I agree that they should not be serialized automatically. The contexts _should_ provide a way to serialize themselves, in absence of which, these contexts will be dropped on the floor at the boundary of the JVM.
