### ISSUE TITLE
AbstractClientBuilder.SHARED_IDLE_CLEANUP_SCHEDULER prevents application from closing

### ISSUE THREAD

**Issue by mathieucarbou** [ReactiveX/RxNetty#105]
```
    HttpClient<ByteBuf, ByteBuf> client = new HttpClientBuilder<ByteBuf, ByteBuf>('localhost', 8080)
            .//withNoIdleConnectionCleanup()
            .withMaxConnections(DEFAULT_MAX_CONNECTIONS)
            .build()

        println client.submit(HttpClientRequest.createPost('/api/profile/login')
           // [...]
          .toBlockingObservable().last()

        client.shutdown()
```

Without `withNoIdleConnectionCleanup`, a static 1-thread scheduler is created and prevents application from closing.

=> Why it is shared ? Could it just be instanciated per client, since each client aslo schedules its own cleanup task and delay ? Ansi since each client can handle a lot of connections, there shouldn't be so much client instances within an app ?

Thank you ;-)

**Comment by NiteshKant** [comment]
> > > With or without withNoIdleConnectionCleanup, a static 1-thread scheduler is created and prevents application from closing.

I will make the thread used by the default executor as a daemon.

> > > Why it is shared ? Could it just be instanciated per client, since each client aslo schedules its own cleanup task and delay ?

Default is a shared cleanup scheduler, one can use a different scheduler per client using this method:

```
new ClientBuilder("localhost", 8080).withPoolIdleCleanupScheduler(Executors.newScheduledThreadPool(1));
```

> > > since each client can handle a lot of connections, there shouldn't be so much client instances within an app ?

An RxClient is dedicated to a host+port combination (the interface supports one RxClient dedicated to a pool of homogeneous servers) so an application will have as many clients as the number of hosts it connects to. All the resources used by an RxClient like eventloops, cleanup threads, etc. can be shared and hence an RxClient does not have any overhead per se, so there isn't an issue creating multiple clients.

**Comment by mathieucarbou** [comment]
Ok! Thank you for the very fast answers :-) I will wait for the new version.
