### ISSUE TITLE
Remove numerus dependency from core

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#114]
Currently numerus is being used for LongAdder an alternate implementation of which is available in netty-common which we already depend on.

**Comment by NiteshKant** [comment]
We were using LongAdder from numerus. Now using netty's internal backport of the same.

**Comment by headinthebox** [comment]
Cool; that caused me some heartburn before.

**Comment by NiteshKant** [comment]
:) yeah it wasn't required. Keep the dependency tree lean is the mantra!
