### ISSUE TITLE
Tons of doc comment errors

### ISSUE THREAD

**Issue by headinthebox** [ReactiveX/RxNetty#118]
Trying to build with Java 8 and I get tons of erros in doc cemments :-(

```
RxNetty/rx-netty/src/main/java/io/reactivex/netty/protocol/http/sse/SSEInboundHandler.java:30: error: self-closing element not allowed
 * A handler to insert {@link ServerSentEventDecoder} at a proper position in the pipeline according to the protocol. <br/>
```

**Comment by NiteshKant** [comment]
Thanks @headinthebox !
So ideally we will have to add these validations to the codestyle plugin we have so that we can catch these early.
@quidryan , any plans to add these to the gradle template?

@headinthebox If this is blocking you, you can add this ([source](http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html)):

```
if (JavaVersion.current().isJava8Compatible()) {
    allprojects {
      tasks.withType(Javadoc) {
        options.addStringOption('Xdoclint:none', '-quiet')
      }
    }
  }
```

temporarily to the build file.

**Comment by headinthebox** [comment]
Thanks; don't understand why Java 8 is so picky about this.

**Comment by NiteshKant** [comment]
@headinthebox yeah "self-closing element not allowed" sound insane as it is a valid HTML.

**Comment by quidryan** [comment]
The plan is to support RxJava going to a new github organization via a new Gradle plugin. I'd then port that plugin back for NetflixOSS, so give it a few weeks. I just put this change into the RxJava version: https://github.com/nebula-plugins/gradle-rxjava-project-plugin/commit/d755bb771ee6e94b2c36c5fac97f0ac8e24439b7

**Comment by NiteshKant** [comment]
As per PR #201 doclint has been disabled for java8.

**Comment by quidryan** [comment]
Nothings going to happen on gradle-template.  We're redesigning it, you can see an incarnation of it in https://github.com/nebula-plugins/gradle-rxjava-project-plugin. That already disables the lint check in Java 8.

**Comment by gorzell** [comment]
Fixing the documentation is still a better option than disabling it by
default ;-).

**Comment by quidryan** [comment]
I guess on a new project that's true. Existing projects haven't had it on
for literally a decade. It's a pretty big change to slip into a JVM
release. Why turn it on after all these years?

**Comment by gorzell** [comment]
Probably to push people in the "right" direction.
