### ISSUE TITLE
"Transfer-encoding: chunked" not set for HTTP POST request.

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#119]
Looking at the code in `ClientRequestResponseConverter.write()`:

``` java
            if (rxRequest.getHeaders().hasContent()) {
                if (!rxRequest.getHeaders().isContentLengthSet()) {
                    rxRequest.getHeaders().add(HttpHeaders.Names.TRANSFER_ENCODING, HttpHeaders.Values.CHUNKED);
                }
```

`rxRequest.getHeaders().hasContent()` returns true if either content-length is set to be none zero, or "Transfer-encoding: chunked" is set. So the next "if" will not be executed if content length is set, or is executed but has no effect because transfer-encoding header is already set.

**Comment by NiteshKant** [comment]
I did not completely understand the description but answering to the issue subject: Yes, it is required to either set content length or transfer-encoding: chunked for an HTTP 1.1 connection.

This is what the above code is doing, i.e. set the transfer-encoding header if there is no content length set for requests having a content.

Is there a particular issue/behavior you are debugging?

**Comment by allenxwang** [comment]
I am debugging an issue where I have added a RawContentSource to a POST request without setting the content-length or transfer-encoding header, and the server has problem handling the request because neither content-length nor transfer-encoding header is received on the server side. 

The problem is that in the above case, even if the the request has ContentSource, rxRequest.getHeaders().hasContent() returns false, so the code following it to set the transfer-encoding header is bypassed completely.

So it seems to me that the intention is to add transfer-encoding header automatically on caller's behalf, but it is not happening. 

Perhaps `if (rxRequest.getHeaders().hasContent())` should be replaced with `if (rxRequest.hasContentSource())` at the beginning.

**Comment by NiteshKant** [comment]
Your understanding seems correct. I think we should check for hasContent()
|| hasContentSource(). Do you want to fix this?

**Comment by allenxwang** [comment]
Sure. Will send a PR.

**Comment by allenxwang** [comment]
Any reason why we still need to check for rxRequest.headers().hasContent() in the first "if" as part of "or"? 

If there is no content source, we can simply execute the following code block, correct?

``` java
if (!rxRequest.getHeaders().isContentLengthSet() && rxRequest.getMethod() != HttpMethod.GET) {
         rxRequest.getHeaders().set(HttpHeaders.Names.CONTENT_LENGTH, 0);
}
allWritesListener.listen(ctx.write(rxRequest.getNettyRequest()));
```
