### ISSUE TITLE
Websockets Proposal

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#125]
### Scope

Netty supports websockets out of the box and hence it can be used within RxNetty with minimal effort (defining appropriate PipelineConfigurator to add websocket encoder/decoder). 
However, if the websockets implementation has to leverage RxNetty's HTTP abstraction (primarily of Client/Server request/response objects) few changes will be required in RxNetty.
In addition to these changes, following the philosophy of RxNetty, we would like to look into what can be done to make the usage of websockets in netty easier.
This proposal is aimed at providing these high level constructs in RxNetty to support websockets.
##### Client

Currently RxNetty's [HttpClientRequest](https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/protocol/http/client/HttpClientRequest.java) does not support a stream of content, instead it has an iterative content source [ContentSource](https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/protocol/http/client/ContentSource.java).
The reason for having this iterative contract instead of an Observable was the ability to apply backpressure from RxNetty in case, the client is too fast as compared to the underlying framework sending data over the wire.
However, it does impose a restriction for cases where there is a need of a stream of content, as is in this case, since a websocket connection is full duplex.

We have a few options here:
- Do away with the current ContentSource model in favor of an Observable which provides us the streaming support we need but sacrifices the backpressure capabilities.
- Create an extended WsClientRequest class which extends HttpClientRequest and adds an additional method to get content as an Observable. We can handle backpressure later when RxJava defines a backpressure contract as discussed [here](https://github.com/Netflix/RxJava/issues/1000)
- Expose the underlying netty's channel to the user so one can write the client side websocket frames anytime on the underlying channel. 
##### Server

There is no API change required for the server side as it does support streaming of request and response content.
### Contract

Provided we do the necessary changes to the API as described above, we should be able to provide the following 
constructs to handle websockets by client and server:
##### Client

```
Observable<HttpClientResponse<? extends WebSocketFrame> RxNetty.createWebSocketRequest(String uri);

```
##### Server

```
HttpServer<? extends WebSocketFrame, ? extends WebSocketFrame> RxNetty.createWebSocketServer(int port, RequestHandler<? extends WebSocketFrame, ? extends WebSocketFrame> handler)

```

Both the above will leverage the underlying more flexible ways to create websocket clients and servers as is the case with other factory methods in [RxNetty](https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/RxNetty.java)
The important point above is that both client and server will handle request/response content as netty's [WebSocketFrame](http://netty.io/4.0/api/io/netty/handler/codec/http/websocketx/WebSocketFrame.html).
### Higher level Clients/Servers

By looking at the above contract it is obvious that most of the users of this feature will have to write some boiler-plate code to implement clients and servers. The boiler plate code will typically be to handle a response, handle ping, close frames and delegate other frames handling to application defined logic.
So it sounds relevant for RxNetty to have out of the box client and server handlers that can have the boiler plate code and delegates the "processing" of these frames to user-defined entities.
### JSR 356

[JSR 356](http://www.oracle.com/technetwork/articles/java/jsr356-1937161.html) defines a standard how java applications can handle websockets. 
At this point it seems prudent to leave this to [karyon](https://github.com/Netflix/karyon) to provide an extension to RxNetty for JSR 356 as one of the ways of handling websockets. This is following the philosophies of RxNetty to have less opinions about how people should use any feature RxNetty provides. Hence, we do not want to commit to any standard on top of websockets protocol inside RxNetty.
### Reactive Streams

[Reactive Streams](http://www.reactive-streams.org/) is an initiative to provide a standard for asynchronous stream processing with non-blocking back pressure on the JVM. We will be implementing this standard sometime down the line in RxNetty and this websocket proposal should keep in mind that in the near future it should be possible to build the reactive streams implementation on top of this.

**Comment by NiteshKant** [comment]
With PR #196 RxNetty has support for websockets.

I am leaving this issue open as of now to discuss any changes to the design and discuss things like:
- High level client/servers as described in this issue's description.
- Fallback to other protocols in case the server does not support websockets i.e. a higher level client like

**Comment by chen56** [comment]
I hope when the client websocket request arrival, server can visit http request head(cookies),  I did not find any api for it ？

**Comment by tbak** [comment]
Currently RxNetty WebSocket server does transparently (for the RequestHandler) upgrade to WebSocket channel, without giving a chance for the server to investigate header/cookie values.

#202 will address this issue.

**Comment by chen56** [comment]
Thank you

**Comment by NiteshKant** [comment]
@chen56 0.5.x supports a way to look at the HTTP request before accepting a websocket upgrade

**Comment by chen56** [comment]
@NiteshKant Thank you, waiting for your release 0.5
