### ISSUE TITLE
ServerSentEventEncoder does not produce valid output

### ISSUE THREAD

**Issue by tbak** [ReactiveX/RxNetty#141]
RxNetty's SSE encoder does not produce valid output. If you look at spec (http://www.whatwg.org/specs/web-apps/current-work/multipage/comms.html#event-stream-interpretation), the ServerSentEventDecoder is pretty close following it. So for example if we get on the wire

event: add
data: something
id: 1

It will be mapped to ServerSentEvent object ServerSentEvent("1", "add", "something").

However the encoder will just produce for such event just one line of this kind:

add: something

And small naming improvement - eventName is described as eventType in the spec.

**Comment by NiteshKant** [comment]
cc @g9yuayon 

@tbak makes sense to me.

So, this is what I understand which should be possible
- Write an event with id, name and data (as it is today) which writes this on the wire

```
event: <name>
data: <data>
id: <id>
```
- Write an event with only name and data which writes this on the wire

```
event: <name>
data: <data>
```
- Write an event with only id and data which writes this on the wire

```
data: <data>
id: <id>
```
- Write an event with only data which writes this on the wire:

```
data: <data>
```

The usecase of above would predominantly be to send multiple data attributes per event name or event name + id combination.
