### ISSUE TITLE
JSR 311 implementation for RxNetty

### ISSUE THREAD

**Issue by diptanu** [ReactiveX/RxNetty#184]
Does it makes sense to have a JSR 311 implementation on top of RxNetty or is this beyond the scope of this project?

I want a way to hook JAX-RS annotated objects with RxNetty's HttpServer. Or, may even be a way to map implementation of RxJava's rx.functions.Action interface to HttpServer would be useful.

**Comment by benjchristensen** [comment]
If we do this they should be a separate module, not part of rxnetty-core.

**Comment by NiteshKant** [comment]
@diptanu this is the area which [karyon](https://github.com/Netflix/karyon) plays in as this gets more into an application domain. Karyon already has a jersey extension (1.x) on top of rx-netty here: https://github.com/Netflix/karyon/tree/master/karyon-jersey-blocking

**Comment by jeje** [comment]
Not sure if this would help, but I created [Grapi](https://github.com/kalixia/Grapi) for a similar need a few months ago.

In short, Grapi is not really a JAX-RS engine, but more an APT processor generating Netty handlers based on JAX-RS annotated resources. This has the benefit of avoiding the runtime _crap_ of JAX-RS containers (although there is still a small dependency on a Jersey class) and eases debugging as the Netty handlers are generated as Java source code, hence something you can easily debug.
Moreover generated Netty handlers only contains needed code based on what your JAX-RS resources do/need.

**Comment by NiteshKant** [comment]
@jeje thanks for sharing your work. It certainly is an interesting approach to generate netty handlers for JAX-RS resources.
In karyon I carried forward the runtime of JAX-RS and it isn't that nice :) I will look into Grapi to see if I can use it within karyon!

@diptanu I am closing this issue as this is out of the current scope of RxNetty.

**Comment by jeje** [comment]
@NiteshKant feel free to reach me if I can help ;-)
