### ISSUE TITLE
Channel implementation replacement restrictions

### ISSUE THREAD

**Issue by tbak** [ReactiveX/RxNetty#191]
Currently it is possible to set different `Channel` implementation only for `InetSocketAddress` address family. Other practical use case that does not fall into this category is `LocalChannel` for in VM communication. The problem comes from the fact that `ServerInfo` class is used throughout a code, which implicitly ties everything to IP stack.

To fix this problem, ServerInfo shall be replaced with `InetSocketAddress` class, and all RxNetty interfaces should use `SocketAddress`, so any address family can be supported.

I made a quick and dirty hack to get `LocalChannel` working. It roughly illustrates the code base size that must be touched: https://github.com/tbak/RxNetty/commit/e8c50b54ddd96b69b3261bd84b774c43d092fe7b

**Comment by NiteshKant** [comment]
This is interesting @tbak 

Do you think as an alternate approach, adding localAddress in ServerInfo would be less disruptive?
The server and client can then adapt to this twin behavior in ServerInfo.

**Comment by NiteshKant** [comment]
@tbak do you want to go ahead with the localAddress in `ServerInfo` solution which is less disruptive?

**Comment by tbak** [comment]
`ServerInfo` is package private class, so impact will be only on the internal implementation. We would need also a new set of factory methods in RxNetty that take SocketAddress. I think it is better wait some more time, and see how we can refactor this code in a more coherent way.

**Comment by NiteshKant** [comment]
0.5.x supports use of `SocketAddress` on both client and server
