### ISSUE TITLE
Move SSE related class to the http package

### ISSUE THREAD

**Issue by gorzell** [ReactiveX/RxNetty#205]
Right now things related to SSE are in a text package, which doesn't make a lot of sense since SSE is an http dependent protocol.  Also websockets are a sub package of HTTP so this change would make SSE consistent with that as well.

**Comment by NiteshKant** [comment]
:+1: We should not have SSE over text option.

@jstnbckr @g9yuayon is mantis using the SSE over text codecs? Is it ok to remove them and have SSE only in HTTP?

If it's ok with everyone, I will deprecate all the existing SSE over text codecs and remove them after 1 release cycle.

**Comment by g9yuayon** [comment]
As far as I know, we're not using text codecs. That said, moving to HTTP
makes more sense as SSE is part of HTML 5 spec and is mainly used for HTTP.

**Comment by NiteshKant** [comment]
Thanks @g9yuayon 

I will deprecate the text codecs in 0.3.12 and we can remove them in 0.3.13 and move the required classed under HTTP package.

@gorzell I hear that you will work on this :)
