### ISSUE TITLE
Deprecate all SSE classes in io.reactivex.netty.protocol.text.sse

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#209]
In relation to issue #205 we need to first deprecate these classes in the io.reactivex.netty.protocol.text.sse package so that we can delete some and move the other to the io.reactivex.netty.protocol.http.sse package in the next release.

**Comment by gorzell** [comment]
I have this mostly done.

What I did was move the existing classes and replaced them with proxies that extend the originals.  These proxies are marked as deprecated.

**Comment by NiteshKant** [comment]
@gorzell sounds good, I will wait for your PR then. In case I need to release 0.3.12 sooner, will punt this to 0.3.13

**Comment by gorzell** [comment]
I'll try to wrap this up today.  It has been a bit tricky because some tests fail sporadically for me and the Context tests still fail every time.
