### ISSUE TITLE
HttpClient should cancel request write & response processing on unsubscription

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#21]
Currently HttpClient cancels the connection subscription when the caller of HttpClient.submit() unsubscribe. This in turn closes the connection.
The relevant code is here: 

https://github.com/Netflix/RxNetty/blob/master/src/main/java/io/reactivex/netty/protocol/http/HttpClientImpl.java#L71

Ideally, it should do the following:

1) If write is not completed, cancel write, which if successful should close connection.
2) If the response is not completed, we wait for response to complete and then close the connection.

In the above statements, close the connection in presence of connection pooling (https://github.com/Netflix/RxNetty/issues/20) would signify connection returning to pool. In such a case, the connection should be in a sane state to re-use i.e. no read/write should be pending.

**Comment by allenxwang** [comment]
I was under the impression that if the Observer is unsubscribed, the channel should be closed in current implementation. But it does not seem to be true. Here are the steps I observed during debugging:
- Request is successfully written to the pipeline and response is also received in the pipeline. onCompleted() method of the Observer that is subscribed to `Observable<HttpResponse>` is called.
- the above Observer is automatically unsubscribed
- Line `connectSubscription.unsubscribe();` inside HttpClientImpl.submit() is called. However, stepping into this call shows that the internal state is already "unsubscribed", so nothing really happened. Another observation is that the method `ObservableConnection.close()` is never invoked.

So it seems that the channel still remains open.

**Comment by NiteshKant** [comment]
> > Line connectSubscription.unsubscribe(); inside HttpClientImpl.submit() is called. However, stepping into this call shows that the internal state is already "unsubscribed", so nothing really happened.

The unsubscribe from connectObservable does not close the connection as it just means, the subscriber does not want to get any new connections. The connection close is explicit, which does not seem to be happening currently in HttpClient. HttpClient should call close on the connection when the request processing is completed. 
I will fix this issue.

**Comment by NiteshKant** [comment]
Now RxClient does cancel all pending writes on unsubscribe (or connection close) but it does not explicitly close a pooled connection if the response is not yet over.

**Comment by NiteshKant** [comment]
This was fixed as part of #208 in release 0.3.15
