### ISSUE TITLE
Migrate Branch Master -> 0.x

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxNetty#218]
To fit into the build processes of ReactiveX I'd like to switch the default branch from 'master' to `0.x` and then delete master.

The build system will automatically create candidate and release jobs for 0.x, 1.x, 2.x etc branches. 

Can I proceed with this change? Once done it will mean you need to change your "upstream" remote in your local environments.

**Comment by NiteshKant** [comment]
Sounds good. Go ahead.
