### ISSUE TITLE
SSE API is error prone, and lacks flexibility for common usage patterns

### ISSUE THREAD

**Issue by tbak** [ReactiveX/RxNetty#222]
Following #220 issue discussion, here is a list of improvements for SSE:
- make `ServerSentEvent` objects creation more flexible:
  - add single argument constructor to `ServerSentEvent` class with data content, or
  - add static factory methods to `ServerSentEvent`(`ServerSentEvent.sseData(String data)`, `ServerSentEvent.sseWithType(String eventType, String data)`, etc)
- accept String object in SSE encoder, which is interpreted as data field value

**Comment by NiteshKant** [comment]
PR #266 reimplements SSE in the package io.reactivex.netty.protocol.http.sse and the following are the primary changes w.r.t this issue:
- Default `ServerSentEvent` constructor only emits a single data event.
- `ServerSentEvent` class provides three create methods `withEventIdAndType`, `withEventType` and `withEventId` to create events with eventId and eventType.
- Verified that one can directly write a string on an `HttpServer` configured to write SSE. This can be done using `HttpServerResponse.writeString()` method.
- Added another method `HttpServerResponse.writeBytes()` to also write a `ByteBuf`
