### ISSUE TITLE
Simplified Pipeline Configuration API

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxNetty#232]
I'd like to be able to create a request like this:

``` java
RxNetty.createHttpGet(uri.toASCIIString(), PipelineConfigurators.<ByteBuf> sseClientConfigurator())
```

rather than

``` java
RxNetty.createHttpClient(uri.getHost(), uri.getPort(), PipelineConfigurators.<ByteBuf> sseClientConfigurator())
    .submit(HttpClientRequest.createGet(uri.toASCIIString()))
```

**Comment by gorzell** [comment]
It would be nice if there was an overload that could handle a plain URI.

I there a separate issue for moving to a more clear chaining pattern for
the pipelines themselves?

**Comment by benjchristensen** [comment]
I don't know if there is another issue, but there should be for the pipelining. We need to get that figured out soon.

**Comment by NiteshKant** [comment]
@benjchristensen @gorzell look at this issue #303 that elaborates API changes for 0.5.0 milestone and addresses the pipeline configuration as well as URI concerns discussed here.

**Comment by NiteshKant** [comment]
0.5.x provides ways to directly add a `ChannelHandler` to a client/server
