### ISSUE TITLE
help , how to use http request.getContent ()?

### ISSUE THREAD

**Issue by chen56** [ReactiveX/RxNetty#240]
How to use the HttpServer in request.getContent ()?, Request.getContent () is a single value or a stream? The following use StringObservable.stringConcat right? 

                 Observable <String> content = request.getContent (). Map (new Func1 <ByteBuf, String> () {
                     Override 
                     public String call (ByteBuf byteBuf) {
                         return byteBuf.toString (Charset.defaultCharset ()); 
                     } 
                 }); 
                 String fullContent = StringObservable.stringConcat (content) .toBlocking () first ().; 
                 RegisterUserDto user = decodeJsonString (fullContent); 
                 db.save (user);

**Comment by tbak** [comment]
RxNetty provides `HttpObjectAggregationConfigurator` which aggregates user content, so you will always get it in one piece. It has default maxContentLength set to 1MB. This configurator is always present if you create HTTP pipeline configuration by calling `PipelineConfigurators.httpServerConfigurator`, which is what all HTTP-related RxNetty factory methods do (for client side they use `PipelineConfigurators.httpClientConfigurator`, which also injects the aggregator).

Your example above could be rewritten to something like this to be more in Rx style:

``` java
HttpServer<ByteBuf, ByteBuf> server = RxNetty.createHttpServer(port, new RequestHandler<ByteBuf, ByteBuf>() {
    @Override
    public Observable<Void> handle(HttpServerRequest<ByteBuf> request, final HttpServerResponse<ByteBuf> response) {
        return request.getContent().flatMap(new Func1<ByteBuf, Observable<Void>>() {
            @Override
            public Observable<Void> call(ByteBuf byteBuf) {
                String fullContent = byteBuf.toString(Charset.defaultCharset());
                final RegisterUserDto user = decodeJsonString(fullContent);

                // As db.save is potentially blocking call, use Schedulers.io() to execute it
                final Worker worker = Schedulers.io().createWorker();
                final ReplaySubject<Void> result = ReplaySubject.create();
                worker.schedule(new Action0() {
                    @Override
                    public void call() {
                        try {
                            db.save(user);
                            response.setStatus(HttpResponseStatus.CREATED);
                            result.onCompleted();
                        } catch (Exception ex) {
                            response.setStatus(HttpResponseStatus.INTERNAL_SERVER_ERROR);
                            result.onError(ex);
                        }
                        worker.unsubscribe();
                    }
                });
                return result;
            }
        });
    }
}).startAndWait();
```

**Comment by chen56** [comment]
@tbak  Thank you so quick reply, your example is very helpful for me
