### ISSUE TITLE
Is there a good way to compose RequestHandler instances?

### ISSUE THREAD

**Issue by tlockney** [ReactiveX/RxNetty#241]
I've been struggling to figure out a good way to do this and it's quite possible that I'm simply failing to see something obvious, but it seems to me that composing (or chaining is a better way to think of it) RequestHandler instances is rather difficult. I ran into this trying to add in the WebappFileRequestHandler functionality to an existing RESTful service. This seems like a common need, so I'm hoping there's a simple way to do this that I've just overlooked.

**Comment by tbak** [comment]
This would fit into #202. In general, we need a mechanism to define different  pipeline configurations/handlers depending on the provided URI patterns, like path prefix.

**Comment by tlockney** [comment]
@tbak ah, yes, I should have looked at the existing issues in more detail -- the heading didn't jump out at me as being related, but I had been thinking about some of the use cases described while looking into this issue. I'll post any further comments I have there and close this question-by-way-of-an-issue. Thanks!
