### ISSUE TITLE
Guaranteeing sequential notifications from operators/Subjects

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#272]
`Subscriber` does not imply sequential notifications i.e. `onComplete` will not be fired when an `onNext` is executing. Custom subscriber instances are used in the following places:
- [RedirectOperator.RedirectSubscriber](https://github.com/ReactiveX/RxNetty/blob/0.x/rx-netty/src/main/java/io/reactivex/netty/protocol/http/client/RedirectOperator.java#L205) 
- [HttpContextClientChannelFactory.ContextCapturingSubscriber](https://github.com/ReactiveX/RxNetty/blob/0.x/rx-netty-contexts/src/main/java/io/reactivex/netty/contexts/http/HttpContextClientChannelFactory.java#L77)
- [UnicastContentSubject.PassThruObserver](https://github.com/ReactiveX/RxNetty/blob/0.x/rx-netty/src/main/java/io/reactivex/netty/protocol/http/UnicastContentSubject.java#L329)

Although, all the notifications are sent from the eventloop which means we will not have concurrent invocations but we can have re-enterant scenarios, typically when an `onComplete()` or `onError()` is triggered from with an `onNext()`. For this reason, it is imperative that we make sure that the notifications are strictly sequential i.e. they are sent in the order they arrive and are never concurrent.

**Comment by benjchristensen** [comment]
If you have events from multiple threads try to reuse existing RxJava mechanisms for handling this so you don't have to reinvent it ... `merge` for example, or `SerializedSubject` and `SerializedObserver`.

**Comment by NiteshKant** [comment]
Thanks @benjchristensen. I did not know about `SerializedSubject`, exactly what I wanted! I was intending to implement it using `SerializedObserver`

In our case, there are only two places this requires fixing:
- [UnicastContentSubject.PassThruObserver](https://github.com/ReactiveX/RxNetty/blob/0.x/rx-netty/src/main/java/io/reactivex/netty/protocol/http/UnicastContentSubject.java#L329)
- [ObservableConnection.getInput()](https://github.com/ReactiveX/RxNetty/blob/0.x/rx-netty/src/main/java/io/reactivex/netty/channel/ObservableConnection.java#L52)

All other operators feed notifications from these sources.

**Comment by NiteshKant** [comment]
Modified `UnicastContentSubject` to wrap the passed observer with a `SerializedObserver` and `ObservableConnection` to use `SerializedSubject`
