### ISSUE TITLE
Eliminate ClientConfig

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#281]
All clients (`RxClient`, `HttpClient`, `UdpClient`) supports a concept of `ClientConfig`. This concept has multiple issues:
- Config instance is immutable and hence, it requires a builder. This pattern is verbose to use.
- Config instance is set using the `ClientBuilder`. Inheritance does not gel well here as the `AbstractClientBuilder.config()` can not determine the correctness of the config unless we introduce yet another generic parameter.
- `HttpClient` checks the type at runtime i.e. whether it is a `RxClient.Config` or `HttpClientConfig`. This is a side-effect of the inheritance  in the config.
### Proposal

Eliminate `ClientConfig` and fold the methods into the client itself. 
This is inline with the changes proposed in #280, after which the client will have multiple methods of modifying the behavior of the client.

**Comment by benjchristensen** [comment]
Examples would be helpful.

**Comment by NiteshKant** [comment]
@benjchristensen Lemme create a new issue which details API changes pertaining to all issues in [0.5.0 milestone](https://github.com/ReactiveX/RxNetty/milestones/0.5.0)

**Comment by benjchristensen** [comment]
Okay.

**Comment by NiteshKant** [comment]
#303 details the API changes discussed here. It also has examples

**Comment by NiteshKant** [comment]
Available in 0.5.x branch
