### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#3]
The following are my comments on doing the first pass of the netty related code. 
### Bugs
- ObservableHttpClient in the unsubscribe action of the returned subscription calls: connectionPromise.channel().close().sync(); but the channel returned by promise can be null.
- The decoder does not handle chunked + SSE combination as such. 
- ServerSentEventDecoder does a checkpoint() after readFullLine() which does not eliminate re-reading on buffer underflow, which the comment suggests.
### Optimizations

The ServerSentEventDecoder can be optimized as follows:
- It currently does a data copy as it converts data to a string. Instead you can read only the attribute name & the rest can be a view of the underlying ByteBuf. This can help in cases where people want to handle raw ByteBuf. You can have a utility method on Message to get data/value as String.
-  It will be more optimal _not_ to add the created message to the out list as it gets accumulated by the ByteToMessageDecoder. Instead you can just fire a channel read event which will send the created message upstream instantly.
### General code improvement
- ObservableHttpClient.ChannelSetting: I do not see a need for this if you have the bootstrap initialized by the builder or passed to the ObservableHttpClient constructor.
- ConnectionPromise may be better off as package private & be completed with a Channel as opposed to a ResponseWriter.
- You are explicitly using the pooled bytebuf allocator which isn't yet blessed by netty which is why the default is unpooled. You may want to stick to the default which will get upgraded to pooled when it is ripe.
- For content-type & other headers parsing you may want to look at this library: simpleframework: http://search.maven.org/#artifactdetails%7Corg.simpleframework%7Csimple%7C5.1.6%7Cjar It is a very lightweight library & provides useful utilities.
- Looks to me that the RequestCompletionPromise is not required in ObservableHttpClient as you guys are always dealing with endless streams. The current code does not much on it but for cancel, which the user does not have a handle on. 
- RequestWriter creates a new promise from the channel & then return another RequestWrittenPromise. You can just create one RequestWrittenPromise and use it for both.

I haven't yet read the entire code, I will update this issue list if I see anything else. If you want me to see a specific piece of code, let me know.

**Comment by g9yuayon** [comment]
Thanks for the detailed review, Nitesh! I'll update the code accordingly. 

About optimization item 1: to find out where the attribute name is, we will have to read each byte at least once, so the bytes in a bytebuf will be copied. The real saving, then, is deserialization cost if a user does not want a string (the spec says SSE should contain unicode characters) but a deserialized object, right?

**Comment by NiteshKant** [comment]
I was looking more at iterating over the ByteBuf using ByteBuf.forEachByte(), looking for a colon or EOF & then slice the buffer appropriately. forEachByte() does not do a copy.
I agree that the encoding would not be an issue as SSE specifies only UTF-8 but I think the decoder converting to String is too early in the process to do the conversion & it eliminates the possibility of folks dealing with ByteBuf. It is much like the HttpDecoder which decodes into ByteBuf & leaves it for clients to convert it in whichever way required.

**Comment by allenxwang** [comment]
It seems that there can be only one Observer for ObservableHttpClient, as each subscription will start a new connection and unsubscription will cause channel close. Is there a way to handle multiple Observers?

Regarding the comment of chunked + SSE, I am wondering if we can simply leave the HttpClientCodec in the pipeline so that we do not have to deal with both chunked encoding protocol and SSE protocol in one decoder.

**Comment by NiteshKant** [comment]
HttpObjectDecoder generates chunked responses iff the content > max chunk size (defaults to 8192 bytes) or the transfer encoding is chunked. The intent of this decoder is to not accumulate content based on size but generate events based on the protocol i.e. occurrence of a new line. If the transfer encoding happens to be chunked, then the minimum granularity we can go is 1 chunk, otherwise, the granularity is per event.

**Comment by NiteshKant** [comment]
Apart from the ServerSentEventDecoder optimization everything is done. Created a new issue (#30)  for this optimization & closing this issue.
