### ISSUE TITLE
Simple URI mapping

### ISSUE THREAD

**Issue by g9yuayon** [ReactiveX/RxNetty#31]
We'd still need an simple URI mapping that dispatches different handlers to different URI patterns. Mantis already has a few use cases for this function. I'd imagine that URI  mapping is the first thing that most users will need, it would make sense to put it in RxNetty.

**Comment by NiteshKant** [comment]
In the simplest form I guess what you are saying is provide a Map of uri regex Vs Action1 implementations, that the Action1 instance passed to RxServer.start() uses, rite?

https://github.com/Netflix/RxNetty/blob/master/src/main/java/io/reactivex/netty/server/RxServer.java#L60

**Comment by NiteshKant** [comment]
@g9yuayon I would not have time to work on this in the short term, let me know if you want to work on this. In that case, I would recommend you to wait till I am done with the latest changes in APIs.

**Comment by g9yuayon** [comment]
No worries, @NiteshKant. In that case I'll work on it.

**Comment by NiteshKant** [comment]
This will be covered by #286. Closing this as duplicate.
