### ISSUE TITLE
UnicastContentSubject GC issues

### ISSUE THREAD

**Issue by daschl** [ReactiveX/RxNetty#312]
In addition to the other issues, it looks like there is a big issue in terms of GC and/or a leak. Here is a comparison to the same code running (load against a Couchbase cluster). AsyncSubject vs UnicastContentSubject. Btw I expected a little bit more GC since more stuff is done, but this drastic difference seems weird (note the 2s vs 50s gc pause time in a 3 min run).

For some context: that comes from 10k ops/s by fetching docs from the server. But in this test its against nonexistent keys, so the buffers are empty.. just wanted a baseline :)

AsyncSubject

![screen shot 2015-01-15 at 15 12 02](https://cloud.githubusercontent.com/assets/29086/5758809/ef5e8bbc-9cc8-11e4-9bc4-5c8f93176737.png)

![screen shot 2015-01-15 at 15 12 15](https://cloud.githubusercontent.com/assets/29086/5758813/f414a6f0-9cc8-11e4-845e-24dc1f47c1e1.png)

UnicastContentSubject

![screen shot 2015-01-15 at 15 13 21](https://cloud.githubusercontent.com/assets/29086/5758833/1b053bda-9cc9-11e4-87e0-a98098efc8c1.png)

![screen shot 2015-01-15 at 15 13 31](https://cloud.githubusercontent.com/assets/29086/5758837/210d440a-9cc9-11e4-93ba-1411c05a525f.png)

**Comment by daschl** [comment]
I've been playing around a bit with timings and it seems that a much shorter timeout doesn't have as much impact as longer ones. This indicates to me that it's because the timers are getting moved out of the young gen making them more costly to be cleaned up.

Any idea how we can work around this to some degree?

**Comment by daschl** [comment]
@NiteshKant @benjchristensen one thing I found as a potential improvement is to only schedule the call when one is still actually unsubscribed. Because currently the disposeIfNotSubscribed() is still called even if one is already subscribed, paying the penalty there too.

want me to submit a PR for this as well?

**Comment by daschl** [comment]
#313 related.

**Comment by NiteshKant** [comment]
0.5.x has no `UnicastContentSubject` and no unnecessary buffering of data.
