### ISSUE TITLE
0.4.5-RCx bytebuf leak issue

### ISSUE THREAD

**Issue by imperatorx** [ReactiveX/RxNetty#321]
A simple http server with the following basic handler:

``` java
return response.writeBytesAndFlush("foo".getBytes());
```

causes a "LEAK: ByteBuf.release() was not called before it's garbage-collected" waring after some thousands of http requests on 0.4.5-RCx. Version 0.4.4 seems unaffected and works fine.

**Comment by NiteshKant** [comment]
I think you are facing issue fixed in this PR: https://github.com/ReactiveX/RxNetty/pull/320
The fix is released in 0.4.5

**Comment by NiteshKant** [comment]
@imperatorx Can I close this issue if it works on 0.4.5?

**Comment by imperatorx** [comment]
Yes, thank you. The leak is gone in 4.5.
