### ISSUE TITLE
Possible issue in HttpServerResponse.writeOnChannel

### ISSUE THREAD

**Issue by rstoyanchev** [ReactiveX/RxNetty#326]
The code on this line https://github.com/ReactiveX/RxNetty/blob/1d4795b31c1c307f74145bcb2ba0f81732bacf8c/rxnetty/src/main/java/io/reactivex/netty/protocol/http/server/HttpServerResponse.java#L189 looks like a sure ClassCastException. Given the if condition on line 169, at this point shouldn't msg be an instance of HttpServerResponse?

I can't confirm the issue since I can't quite see how msg could come to be an instance of HttpServerResponse. Apologies if this isn't an actual issue.

**Comment by NiteshKant** [comment]
Thanks @rstoyanchev for reporting the issue.
Looks like this is dead code and will never be executed. The code was trying to optimize multiple writes for zero-length content responses but it looks like it does not get executed in that case too.
I will remove the code.

**Comment by NiteshKant** [comment]
This code path is removed in 0.5.x
