### ISSUE TITLE
Problems with synchronized channel connection and callbacks on ConnectException

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#33]
In RxClientImpl, channels are connected synchronously:

final ChannelFuture f = clientBootstrap.connect(serverInfo.getHost(), serverInfo.getPort()).sync();

This causes Ribbon junit test failure on retries if the retry happens on the same thread. The exception received is BlockingOperationException.

If removing sync() call, then this JUnit test will fail as Observer.onCompleted() is called unexpectedly:

```
@Test
public void testConnectException() throws Exception {
    HttpClientBuilder<FullHttpRequest, FullHttpResponse> clientBuilder =
            new HttpClientBuilder<FullHttpRequest, FullHttpResponse>("localhost", 81);
    HttpClient<FullHttpRequest, FullHttpResponse> client = clientBuilder.channelOption(
            ChannelOption.CONNECT_TIMEOUT_MILLIS, 1000).build();
    FullHttpRequest request = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.GET, "/");
    Observable<ObservableHttpResponse<FullHttpResponse>> response = client.submit(request);
    final CountDownLatch latch = new CountDownLatch(1);
    final AtomicReference<Throwable> ex = new AtomicReference<Throwable>();
    response.subscribe(new Action1<ObservableHttpResponse<FullHttpResponse>>() {
        @Override
        public void call(ObservableHttpResponse<FullHttpResponse> t1) {
        }

    }, new Action1<Throwable>() {
        @Override
        public void call(Throwable t1) {
            ex.set(t1);
            latch.countDown();
        }
    }, new Action0() {

        @Override
        public void call() {
            System.err.println("OnCompleted called");
            latch.countDown();
        }

    });
    latch.await();
    System.err.println(ex.get());
    assertNotNull(ex.get());
}
```

The output shows that OnCompleted is called, instead of OnError.

**Comment by allenxwang** [comment]
We can add a ChannelFutureListener to the channel connect operation and call Observer.onError() if the operation failed. This seems to ensure that the right exception is given to the Observer.

**Comment by NiteshKant** [comment]
Looks like the connect failure does not flow through the pipeline, which is an issue. So, the only way to fix this is what you have suggested. 
The sync() call in RxClient is certainly wrong. 
Allen, will you take this up?

**Comment by allenxwang** [comment]
Sure. Will send a pull request soon.

**Comment by NiteshKant** [comment]
@allenxwang In the interest of better maintainability, having all observer callbacks in a single place would be beneficial. In this case, it will be ConnectionLifecycleHandler.
