### ISSUE TITLE
ReadTimeout is not respected by the client reusing a pooled connection

### ISSUE THREAD

**Issue by yurgisbaykshtis** [ReactiveX/RxNetty#344]
Here is the unit test for io.reactivex.netty.protocol.http.client.HttpClientPoolTest.java

Seems like a major issue to me - leads to the scenario when request to a dead/non-responding server could be stuck forever.

```
    @Test(expected=ReadTimeoutException.class)
    public void testReadtimeoutForReusedConnection() throws Exception {
        HttpClient.HttpClientConfig conf = new HttpClient.HttpClientConfig.Builder().readTimeout(1, TimeUnit.SECONDS).build();
        client = newHttpClient(1, PoolConfig.DEFAULT_CONFIG.getMaxIdleTimeMillis(), conf);
        //first make a normal request with no timeout to let it get to the pool
        submitAndWaitForCompletion(client, HttpClientRequest.createGet("/"), null);
        //now try the pooled connection with response delay > timeout
        submitAndWaitForCompletion(client, HttpClientRequest.createGet("test/timeout?timeout=10000"), null);
    }
```

**Comment by yurgisbaykshtis** [comment]
The root cause of the issue seems to be in ReadTimeoutHandler where ReadTimeoutTask is never rescheduled after destroy() call. I guess that was supposed to happen in handlerAdded()/initialize() call chain, but due to state == 2 is not working (possibly introduced by https://github.com/netty/netty/issues/143). 
It is not clear what would be a proper fix.

**Comment by NiteshKant** [comment]
@yurgisbaykshtis thanks for reporting the issue and apologies for the delayed response.

Yes, indeed your analysis is correct and the reason looks like that the `ReadTimeoutHandler` does not support `handlerAdded` -> `handlerRemoved` -> `handlerAdded` cycles. It also does not support extending the handler to modify this behavior. Let me think more about this.

**Comment by NiteshKant** [comment]
I did not notice that @jjteo74 has provided a PR #346 to fix this.
