### ISSUE TITLE
Override DefaultErrorResponseGenerator

### ISSUE THREAD

**Issue by hovsater** [ReactiveX/RxNetty#375]
So RxNetty ships with a `DefaultErrorResponseGenerator` that handles errors that might occur. How would I go about overriding it so I can handle the errors instead?

I already have behaviour for how to handle unexpected errors and I want to return JSON if something unexpected happens.

Edit: I just noticed the methods `.withErrorHandler()` and `.withErrorResponseGenerator()`. I'm guessing those will solve my problem?

**Comment by NiteshKant** [comment]
> >  I just noticed the methods .withErrorHandler() and .withErrorResponseGenerator(). I'm guessing those will solve my problem?

Correct.

FYI: Starting [0.5.x](https://github.com/ReactiveX/RxNetty/wiki/0.5.x-FAQs), these methods are removed and a more idiomatic way via `Observable.onErrorResumeNext()` within your `ConnectionHandler`/`RequestHandler` will be the way of sending default error responses.
