### ISSUE TITLE
Split into protocol specifc modules

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#384]
Today, all protocols are bundled into a single module. Over time, this can explode the dependency tree as we add new protocols. 
Once, we do this, we can also break the modules as different projects having different release cycles.

As of today, I see the following modules:
- **rxnetty-core** (Common functionality for all protocols)
- **rxnetty-tcp** 
- **rxnetty-http** (HTTP 1.1/2.0, WS)
- **rxnetty-udp**
- **rxnetty-tcp-spectator** (TCP spectator plugin)
- **rxnetty-http-spectator** (HTTP spectator plugin)
- **rxnetty-udp-spectator** (UDP spectator plugin)

**Comment by NiteshKant** [comment]
\cc @pieces029 @daschl @benjchristensen

**Comment by daschl** [comment]
I certainly +1 the idea, it will make it easier for other protocols to adopt!

**Comment by AndrewReitz** [comment]
+1 it will help reduce the amount of dependencies (and keep the method count down) in Android projects.
