### ISSUE TITLE
Completing a Request/Response should remove the Listener from the underlying chanel.closeFuture

### ISSUE THREAD

**Issue by stevegury** [ReactiveX/RxNetty#402]
According to my reading of this code: https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty/src/main/java/io/reactivex/netty/protocol/http/internal/AbstractHttpConnectionBridge.java#L142

It seems that we add a listener responsible for calling onError on the connectionInputSubscriber.
I think I understand why, but the problem I forsee is that when I reuse a connection, it also sends an event, which will add a Listener for every reuse of a connection.

Those listeners are never removed when the request/response complete.

**Comment by NiteshKant** [comment]
Thanks @stevegury for reporting. Yeah it is a memory leak as the `closeFuture()` lives as long as the connection and all these listeners never get cleared up and hence stay till the channel is closed.
