### ISSUE TITLE
writeContent hangs with a response-content as parameter

### ISSUE THREAD

**Issue by gfrison** [ReactiveX/RxNetty#407]
Hello,

I'm trying to upload (multipart request) a file from a web resource:
1. get an image from http server
2. upload it elsewhere with multipart request

unfortunately, when I invoke (2) .writeContent(previousGetReponse.getContent())
the II request hangs without sending any byte.

The process works if I aggregate the (1) response in a 

```
Observable<byte[]>.
```

the running snippet is here
https://gist.github.com/gfrison/8268541eea88bfb76102

What it is wrong in the (2) request?

I'm using the latest 0.5.0-SNAPSHOT version.

Thank you,

**Comment by NiteshKant** [comment]
@gfrison apologies for the delayed response.

It looks like in your code, the content-length for the second request is set more than the content you are writing, so the server is waiting for more content to arrive.

If you change the code to add "Content-length" from:

``` java
Integer.valueOf(cType[1]) + header.length + footer.length
```

to 

``` java
Integer.valueOf(cType[1])
```

The server responds appropriately (as far as I can see)

**Comment by gfrison** [comment]
Thank you so much,

You absolute right and it was my mistake. Sorry for this waste of time...
It works like a charm in _0.5_ but I get a problem with _0.4.11_

https://gist.github.com/gfrison/ef9d9f36151234cf7f14

when I concatenate the chained request with:

``` java
post.withContentSource(Observable.just(Unpooled.copiedBuffer(header)).concatWith(response.getContent()).concatWith(Observable.just(Unpooled.copiedBuffer(footer))));
```

the `response.getContent()` doesn't flush anything.
If I replace it with an `byte[]` that content will be flushed into the second request.

Could you please point me what is wrong?

Thank you so much,
