### ISSUE TITLE
Rpc example

### ISSUE THREAD

**Issue by GrapeBaBa** [ReactiveX/RxNetty#410]
Hi ,
could you provide a rpc example?as rpc usually support pileline , i am not quite sure how to handle the related response for formal request.

**Comment by NiteshKant** [comment]
@GrapeBaBa I am not sure if I agree with the statement "rpc usually support pileline" as it means head of line blocking for all pipelined requests. IOW, I have not used pipelining for RPC libraries.

Is your question more like; whether `RxNetty` supports pipelining? 

If so, then, `RxNetty` `HttpClient`s do not support pipelining and the servers do work with pipelined requests. So, it is a yes and no answer :)

**Comment by GrapeBaBa** [comment]
sorry, maybe i descripe wrong, i just want non-blocking request before the response received. usually using a opaque between request and response. i want to know how to  
do that using rxnetty.

发自我的 iPhone

**Comment by GrapeBaBa** [comment]
hi
will it support pipelining in further version both tcp client and http client? does it mean i cannot using rxnetty for a rpc client now?

发自我的 iPhone

**Comment by NiteshKant** [comment]
I am confused now. When you say pipelining, what exactly do you mean? Are you referring to [HTTP pipelining](https://en.wikipedia.org/wiki/HTTP_pipelining) or something else?

When you say "non-blocking request before response received", do you mean sending concurrent requests to the same server? If so, it is achieved by using multiple connections in case of HTTP. For TCP, you have to build your own protocol on top which supports request multiplexing.

So, you need to be more clear about what you are asking.

**Comment by GrapeBaBa** [comment]
Hi Kant,

Maybe I am not describe clearly. I paste a code, i am not quite sure the code is correct when concurrent rpc invoke? 

```
public class DefaultTransporter {
  private final TcpClient<Request, Response> client = ClientFactory
      .client(new ClientConfiguration());

  private final ConcurrentMap<Integer, CompletableFuture<Response>> responses =
      new ConcurrentHashMap<>();

  private final Scheduler responseSubscribeScheduler = Schedulers.computation();

  public CompletableFuture<Response> dispatch(Request in) {
    final CompletableFuture<Response> responseCompletableFuture = new CompletableFuture<>();
    responses.putIfAbsent(in.getMagicNumber(), responseCompletableFuture);

    client
        .createConnectionRequest()
        .flatMap(
            protocolProtocolConnection -> protocolProtocolConnection.write(Observable.just(in))
                .cast(Protocol.class).mergeWith(protocolProtocolConnection.getInput()))
        .subscribeOn(responseSubscribeScheduler).subscribe(response -> {
          responses.get(response.getMagicNumber()).complete(response);
        });

    return responseCompletableFuture;
  }

}
```

**Comment by NiteshKant** [comment]
Apart from minor things like, you do not need a `subscribeOn()` call there, the code will work fine for concurrent invocations of `dispatch()`. However, it is not guaranteed that all `dispatch()` calls will use the same connection (none of them will, if you do not use connection pooling). If you want to reuse the same connection for concurrent requests, you will have to do something like what [this example](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/ws/messaging/MessagingClient.java) does w.r.t writing all messages as a single stream OR you can write an operator [like this](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-http/src/main/java/io/reactivex/netty/protocol/http/ws/client/OperatorCacheSingleWebsocketConnection.java) that caches the connection, till it is closed.

The reason for the above is that a client closes the underlying connection when the input is unsubscribed. When [using pooling](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-common/src/main/java/io/reactivex/netty/client/pool/PooledConnectionProvider.java), on input unsubscription, the connection is returned to the pool. At any time, a connection is dedicated to a single processing, so two `createConnectionRequest()` subscriptions can not use the same connection concurrently.
