### ISSUE TITLE
Streaming large files using RxNetty (ideally, line by line)

### ISSUE THREAD

**Issue by Crystark** [ReactiveX/RxNetty#417]
Hi,

I'm trying to use RxNetty 0.4.x as an HTTP client to stream a large file (50m) from an HTTP server (Amazon S3). At first, I ran into the following error:

```
io.netty.handler.codec.TooLongFrameException: HTTP content length exceeded 1048576 bytes.
```

So I looked at the [HttpChunkClient](https://github.com/ReactiveX/RxNetty/blob/0.4.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/chunk/HttpChunkClient.java) in the examples and I noticed the HttpClient didn't use the Aggregator of the default HttpClient so removed it and here's what I ended up with:

``` java
RxNetty.createHttpClient(host, port, new HttpClientPipelineConfigurator<ByteBuf, ByteBuf>())
    .submit(HttpClientRequest.createGet(uri))
    .flatMap(r -> {
        return r.getContent()
            .map(content -> new ByteBufInputStream(content));
    });
```

So that seems to work except that i get... chunks ! So I tried to take a look at how `HttpObjectAggregator` works to see if I could do something to make the contents "streamable" but I must say it's not as easy to understand as i'd wish.

So I'm trying to see my options here before i go any further. IMO, the Rx way is suited to what I want to do so my first idea was to use RxNetty but I could also simply use `URL.openStream` inside my own Observable to emit stuff line by line:

```
    InputStream in = uri.toURL().openStream();
    BufferedReader reader = new BufferedReader(new InputStreamReader(in));
    String line;
    while ((line = reader.readLine()) != null) {
        // Do something with the line
    }
```

So my question here is: have I missed something in RxNetty that would do what I'm looking for ? If not would you have any pointers on how I could easily add this to a RxNetty HttpClient ?

Thanks

**Comment by NiteshKant** [comment]
@Crystark you do not need to modify the `HttpObjectAggregator`, instead can add a handler after the `HttpObjectAggregator` to take `ByteBuf` and split them by newlines. [This decoder](http://netty.io/4.0/api/io/netty/handler/codec/LineBasedFrameDecoder.html) should suffice to your needs.

Alternatively, there is a library [RxJavaString](https://github.com/ReactiveX/RxJavaString) that you may find useful here.

**Comment by Crystark** [comment]
Thanks.

I indeed tried to use RxJavaString as I ended up using the AWS SDK to fetch the InputStream from S3 rather than RxNetty (looking forward to [rx-aws-java-sdk-s3](http://mvnrepository.com/artifact/com.netflix.rx-aws-java-sdk) if it ever comes out).
However this did not suffice as RxJavaString doesn't have a helper to read an InputStream by line while it's being downloaded so I ended up creating my own `OnSubscribe` that's i'll probably propose as a pull request for RxJavaString.

Thanks again for your help.

**Comment by Feng-Zihao** [comment]
@Crystark   I'm now working on a http proxy project. I face the same problem as you do.

Your post and @NiteshKant  is helpful.

I've digged a little deeper. What we need, is "direct bytestream forwards".

If you start digging with `PipelineConfigurators.httpClientConfigurator`, you'll find  `HttpClientPipelineConfigurator`  is connected to `HttpClientCodec`, finally with `Decoder` in `HttpClientCodec`.

Inside the `Decoder`, you'll find method `decode()`, I think, with a little modification on this method,  it's not hard to implement a `zero copy server`.

@NiteshKant , am I correct ?
