### ISSUE TITLE
(0.4.x) Can't remove a listener from a MetricEventsPubliser

### ISSUE THREAD

**Issue by mikeweisskopf** [ReactiveX/RxNetty#427]
# Problem description:

At one point Nitesh mentioned adding removeListener() to MetricEventsPublisher [here](https://github.com/ReactiveX/RxNetty/issues/98#issuecomment-44468564), but later changed to use Subscription instead. The rational was "returned Subscription can be unsubscribed to remove the listener". However, it seems to me thats not what actually happens.....instead calling unsubscribe only changes the state of the subscription (for example BooleanSubscription.isUnsubscribed() will return true). However, the listener (MetricsEventsPublisher) remains unchanged. 
# Additional info from Nitesh

Nitesh pointed out the source of the bug [here](https://github.com/ReactiveX/RxNetty/issues/98#issuecomment-144118414)

**Comment by NiteshKant** [comment]
Fixed via #428
