### ISSUE TITLE
Does PooledConnectionProvider detect connection failed and auto reconnect to server when server is up? 

### ISSUE THREAD

**Issue by GrapeBaBa** [ReactiveX/RxNetty#433]
Hi,
Does PooledConnectionProvider detect connection failed when server is down and auto reconnect to server when server is up?

**Comment by NiteshKant** [comment]
The connection pool detects disconnects (dead connections) and purge them from the pool. 
It does **not** "retry in the background" to reconnect when the server is up. All connections are made on demand and pooled after it is established.

**Comment by GrapeBaBa** [comment]
cool.

发自我的 iPhone
