### ISSUE TITLE
[0.4.x] Update to netty 4.1.0.Beta7 reduces throughput by 30%

### ISSUE THREAD

**Issue by Crystark** [ReactiveX/RxNetty#446]
Hi,

I tried updating from RxNetty 0.4.11 to 0.4.13 and i'm having a reduced throughput (approximatly 30%) that seems to be caused by the netty version.

I tested this with this simple code:

``` java
    HttpServer<ByteBuf, ByteBuf> createRxNetty204Server() {
        HttpServer<ByteBuf, ByteBuf> server = RxNetty
            .createHttpServer(port, (request, response) -> {
                return request.getContent()
                    .map(bb -> "" + bb.toString(Charset.defaultCharset()).length())
                    .<Void> map(i -> {
                        response.setStatus(HttpResponseStatus.OK);
                        response.getHeaders().setContentLength(i.length());
                        response.writeString(i);
                        return null;
                    })
                    .finallyDo(() -> {
                        response.close();
                    });
            })
            .withErrorHandler(t -> {
                if (!"Connection reset by peer".equals(t.getMessage())) {
                    L.error("Unexpected error in RxNetty.", t);
                }
                return Observable.error(t);
            });
        return server;
    }
```

I went from a bit over 60k QPS to a bit under 45k QPS on this example benching with wrk2 and sending POST requests.

I also tried 4.1.0.Beta8 and I'm having the same problem. I ended up forcing RxNetty 0.4.13 to use netty 4.0.27.Final and i get back the expected QPS.

However 4.0.27.Final doesn't work fully with rxnetty 0.4.13 (it's hanging in my real case scenario: the proxy server) so i had to revert to 0.4.11

**Comment by Crystark** [comment]
This is actually quite troublesome. 0.4.11 gives me alot of `ClosedChannelException` while 0.4.13 fixes that but makes me loose 30% throughput.

**Comment by Crystark** [comment]
Did a bit more of testing. I have the same throughput problem with netty versions starting at 4.0.31.Final. 4.0.30.Final works fine and has the same performances as 4.0.27.Final

**Comment by NiteshKant** [comment]
@Crystark that is nasty. Any chance you can profile the two runs and see if there is something obvious?

**Comment by Crystark** [comment]
Ok so i profiled the two runs and yeah, there's something obvious: Leak detection costs ALOT more in the newest netty versions than in previous. I'm actually always using `-Dio.netty.leakDetection.level=advanced` when developing. If i remove this option both runs keep the 60k QPS. What is strange though is that this advanced leak detection actually costs nothing in previous versions. Maybe that option just doesn't work in previous netty version ?

Anyway, I'm not sure this should be categorized as an Issue. It may be normal. It's definitely not a problem for production. Let me know your thoughts.

**Comment by NiteshKant** [comment]
@Crystark sorry this slipped off my attention. Yeah advanced leak detection is not recommended for production so I don't think this is an issue per se.
