### ISSUE TITLE
How to send error response when Observable passed into write method fails

### ISSUE THREAD

**Issue by rstoyanchev** [ReactiveX/RxNetty#458]
It seems there is no way to send an error response (e.g. 500 vs 200) once any of the `ResponseContentWriter` write methods is called which commits the response. How does one deal with errors that may occur on the `Observable` passed into the write methods? Technically if the failure occurs before any data is produced, it should still be possible to change the response.

**Comment by NiteshKant** [comment]
RxNetty follows streaming write semantics (just like netty) which means you write parts of HTTP response, as and when you know about them. You write headers when you have enough information to write them and write content as and when you have them available. 
Write but not commit implies caching of headers, which depending on usecase may become an overhead. So, I would not pick that as the default behavior. 

It certainly is possible to defer writing headers as displayed in [this proxy example](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/proxy/ProxyServer.java) which may be the pattern one can follow for representing conditional HTTP status codes.

**Comment by rstoyanchev** [comment]
Thanks for the response. In the proxy example there is response from the target host that you can do flatMap on before calling `write`. What if you had something that returns database records:

``` java
public class PersonRepository {

    public Observable<Person> list() {
        // ...
    }
}
```

How would I defer the call to `response.write(repository.list())`?

**Comment by NiteshKant** [comment]
@rstoyanchev If there is an outbound call that does not follow a metadata and data response structure, it is difficult to map it to a metadata - data structure of HTTP. I can imagine a few ugly ways to defer the writing of headers from a stream of homogeneous objects may be by splitting the stream into the first item and the rest, but as I said they will be ugly :)

If collecting the stream is an option then obviously one can defer the write till everything is received (just like netty’s FullHttpResponse).

How do you envision the API to look like if this case was to be supported cleanly?

**Comment by rstoyanchev** [comment]
Not quite sure but I was thinking that `write` wouldn't really write until the first item and instead propagate any error that occurs before that through the `Publisher<Void>`. Along with that maybe some method on the response that indicates whether the response is committed or not.

Also any application code that wants to force writing immediately can always call `sendHeaders` in which case `write` would know the response is committed anyway.

**Comment by rstoyanchev** [comment]
By the way we've resolved this through the use of a custom operator. Feel free to close this.

**Comment by NiteshKant** [comment]
@rstoyanchev thanks for the update! Do you mind sharing the code for the custom operator?

**Comment by rstoyanchev** [comment]
Sure see [WriteWithOperator](https://github.com/spring-projects/spring-reactive/blob/master/src/main/java/org/springframework/http/server/reactive/WriteWithOperator.java), this is with Project Reactor but the concept is the same.
