### ISSUE TITLE
problems using netflix wrapper for rxnetty

### ISSUE THREAD

**Issue by yairogen** [ReactiveX/RxNetty#459]
I am using the netflix client that wrapps rxnetty.

After running this code:

``` java
rx.Observable<HttpClientResponse<ByteBuf>> responseObservable = httpClient.submit(httpRequest, retryHandler, clientConfig);
```

I then try to read the response content:

``` java
HttpClientResponse response = responseObservable.toBlocking().first();
ByteBuf buf = response.getContent().toBlocking().first();
            int length = buf.readableBytes();

            if (buf.hasArray()) {
                responseBody = buf.array();
            } else {
                responseBody = new byte[length];
                buf.readBytes(responseBody);
            }
```

this sometimes works and sometimes fails on:

io.netty.util.IllegalReferenceCountException: refCnt: 0

```
at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1190)
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1176)
at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1172)
at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:693)
at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:1496)
at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:42)
at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:701)
at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:1491)
at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:42)
```

**Comment by NiteshKant** [comment]
@yairogen RxNetty 0.4.x auto-releases the buffers read by netty. If you need the buffer out of the scope of the `onNext` call from RxNetty, you need to retain the buffer once and release it once you are done. Modifying your code for this case, it would look like:

``` java
ByteBuf buf = response.getContent().doOnNext(ByteBuf::retain).toBlocking().first();
```

and after you are done with the buffer, call:

``` java
buf.release();
```

For more information on reference management of buffers see this [netty wiki](http://netty.io/wiki/reference-counted-objects.html)

**Comment by yairogen** [comment]
This seems to work. I'll need to test firther.

However, please note it is the http response I access out of the scope. I wrap it my own response object by doing this:

```
rx.Observable<HttpClientResponse<ByteBuf>> responseObservable = httpClient.submit(httpRequest, retryHandler, clientConfig);
        return new NettyNetflixHttpResponse(responseObservable.toBlocking().first());
```

and then when getResponse is called on my object I do:

```
ByteBuf buf = httpResponse.getContent().doOnNext(ByteBuf::retain).toBlocking().first();
            int length = buf.readableBytes();

            if (buf.hasArray()) {
                responseBody = buf.array();
            } else {
                responseBody = new byte[length];
                buf.readBytes(responseBody);
            }
            buf.release();
```

Do you see any issues here?

**Comment by NiteshKant** [comment]
Yeah this seems ok.

**Comment by yairogen** [comment]
@NiteshKant 
I have a problem that when using rxnetty synchronously this solution works fine, but when using async it blocks and fails on timeout.

Sync code:

```
val responseObservableSync: Observable[HttpClientResponse[ByteBuf]] = httpClient.submit(clientRequest, retryHandler, clientConfig)
    val response =  responseObservableSync.toBlocking.first()
    LOGGER.info("status: {}", response.getStatus)
    LOGGER.info("content: {}", response.getContent.toBlocking.first());
```

Async:

```
val responseObservable: Observable[HttpClientResponse[ByteBuf]] = httpClient.submit(clientRequestAsync, retryHandler, clientConfig)
      responseObservable.subscribe(new Subscriber[HttpClientResponse[ByteBuf]]() {
        final def onCompleted {
        }

        final def onError(e: Throwable) {
          LOGGER.error("error serving request: {}", e)
        }

        final def onNext(response: HttpClientResponse[ByteBuf]) {
          val status = response.getStatus
          LOGGER.info("content: {}", response.getContent.toBlocking.first());
          LOGGER.info("status: {}", response.getStatus)
        }
      });
```

Any ideas why reading content from response blocks when using it from the subscriber callback?

**Comment by NiteshKant** [comment]
The async example is blocking the eventloop since you are doing a blocking call (`response.getContent.toBlocking.first()`) inside `onNext()`. If the eventloop processing this connection is blocked, it will not give any more callbacks and hence you don't receive the content.

**Comment by yairogen** [comment]
@NiteshKant Thanks. It is very confusing all the async layers here. Why do we need to have both the response and the content async?
Any way - what's the best approach to read the content in the async approach?

**Comment by NiteshKant** [comment]
> > > Why do we need to have both the response and the content async?

RxNetty supports streaming reads of content and headers, so it does not aggregate/collect the response content before giving a callback to the user. So, the content has to be async as it has not been read yet.

> > > what's the best approach to read the content in the async approach?

Have you seen the examples in RxNetty? Here is an example that listens to the content stream:

https://github.com/ReactiveX/RxNetty/blob/0.4.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/helloworld/HelloWorldClient.java#L43

**Comment by yairogen** [comment]
I did look at these examples but here again they use toBlocking. 
In my code, I did the following and I timeout:

```
buf = httpResponse.getContent().doOnNext(ByteBuf::retain).<ByteBuf> map(content -> {
                    return content;
                }).toBlocking().toFuture().get(3, TimeUnit.SECONDS);
```

I'm probably missing something fundamental here. I am wrapping the rxnetty client and I interact with the response outside of the netty scope.

I also need to support both sync and async wrapper API's.

**Comment by yairogen** [comment]
@NiteshKant 
After getting deeper into my problem I think I may have a solution. Please let me know what you think.

Sync code:

```
rx.Observable<HttpClientResponse<ByteBuf>> responseObservable = httpClient.submit(httpRequest, retryHandler, clientConfig);
        HttpClientResponse<ByteBuf> httpResponse = responseObservable.toBlocking().first();
        ByteBuf content = httpResponse.getContent().doOnNext(ByteBuf::retain).toBlocking().first();
        return new NettyNetflixHttpResponse(httpResponse, content);
```

The 'NettyNetflixHttpResponse' constructor code:

```
this.responseByteBuf = responseByteBuf;
        if(responseByteBuf != null){
            int length = responseByteBuf.readableBytes();

            if (responseByteBuf.hasArray()) {
                responseBody = responseByteBuf.array();
            } else {
                responseBody = new byte[length];
                responseByteBuf.readBytes(responseBody);
            }
            responseByteBuf.release();
        }
```

The Async Code:

```
rx.Observable<HttpClientResponse<ByteBuf>> responseObservable = httpClient.submit(httpRequest, retryHandler, clientConfig);

        responseObservable.subscribe(new Subscriber<HttpClientResponse<ByteBuf>>() {
            @Override
            public void onCompleted() {
            }

            @Override
            public void onError(Throwable e) {
                LOGGER.error("error serving request: {}", e, e);
                responseCallback.failed(e);
            }

            @Override
            public void onNext(HttpClientResponse<ByteBuf> byteBufHttpClientResponse) {

                byteBufHttpClientResponse.getContent().subscribe(new Subscriber<ByteBuf>() {
                    @Override
                    public void onCompleted() {
                    }

                    @Override
                    public void onError(Throwable e) {
                        LOGGER.error("error serving request: {}", e, e);
                        responseCallback.failed(e);
                    }

                    @Override
                    public void onNext(ByteBuf content) {
                        content.retain();
                        responseCallback.completed(new NettyNetflixHttpResponse(byteBufHttpClientResponse, content));
                    }
                });
            }
        });
```

This seems to work ok. I think the code will break if the Http response doesn't contain a content. In that case can I assume that the getContent on the response object will always return null?

**Comment by NiteshKant** [comment]
There is an assumption in this code, it assumes there is only ever a single `ByteBuf` in the content. It is ok, if you are making sure the client aggregates the content (if your usecase doesn't require streaming content). 0.4.x defaults to aggregated content so you are fine on that front.

`getContent()` never returns a `null`. If there is no content, it will return an empty `Observable` i.e. it just emits an `onComplete()` event.

It appears from the limited code I can see is that you are providing a different async abstraction from your client than Rx. Is that correct?

**Comment by yairogen** [comment]
You are correct in your assumptions. And indeed we have an existing interface that supports async and users pass in their callback listener which we delegate to from rxnetty async. 

So, if you think that under our assumptions this is a valid code, I think we can close this issue. 

I think I just need to call my callback completed from Netty completed and not from on next. 

Thanks

**Comment by NiteshKant** [comment]
> > > I think I just need to call my callback completed from Netty completed and not from on next.

Since, there is only a single `ByteBuf` in the content, it doesn't really matter as `onComplete()` will be called immediately after `onNext` but yeah it does not hurt either.

> > > So, if you think that under our assumptions this is a valid code, I think we can close this issue.

Yeah, the code looks good. Closing.
