### ISSUE TITLE
Does it need a server side heartbeat mechanism when using pooled connection provider

### ISSUE THREAD

**Issue by GrapeBaBa** [ReactiveX/RxNetty#461]
Hi,
Now I am not quite sure if it also need a server side heartbeat mechanism when client using pooled connection provider to create a RPC system? Can you give me some advice?

**Comment by NiteshKant** [comment]
Whenever you are pooling connections, you assume that the connections would be alive for a longer duration than one request-response. There are many ways to make sure that the connection is alive, eg: application level heartbeats (server and client), TCP keep alive, more utilized connections. Connection pooling in RxNetty does not do any of these and leave the responsibility to the users to choose what is best for their environment.

So, you need some mechanism to keep the connection open, server side heartbeats being one of them.
