### ISSUE TITLE
4.X - AbstractClientBuilder : creation of MetricEventsListener not useful 

### ISSUE THREAD

**Issue by fzakaria** [ReactiveX/RxNetty#464]
Hello,

I'm trying to follow along the guide for registering MetricListenerFactory.
The README.md outlines using the global registration

For example

```
        RxNetty.useMetricListenersFactory(new SpectatorEventsListenerFactory());
```

This however doesn't seem useful as it will create MetricsEventListeners in the _AbstractClientBuilder_ that are not accessible

```
public abstract class AbstractClientBuilder<I, O, B extends AbstractClientBuilder, C extends RxClient<I, O>> {
...
public C build() {
       ...
        C client = createClient();
        if (null != eventListenersFactory) {
            MetricEventsListener<? extends ClientMetricsEvent<?>> listener =
                    newMetricsListener(eventListenersFactory, client);
            client.subscribe(listener);
        }
        return client;
    }
```

Am I missing a piece of the puzzle here or is this not useful / bug ?

**Comment by NiteshKant** [comment]
@fzakaria The idea of the global metric listener factory is to specify a metrics listener for **all** clients created in the JVM without having to specify them separately for each client individually.

This usually is useful if you as an application writer use different libraries that create different clients. As, you do not have control over the metrics they use, you can control the metrics publishing for all clients globally.

If you need to control which metric listener to use individually for each client/server, you can instantiate and subscribe that listener to the client in question. This way you will have access to the listener instance and control on what you would want to do per client.

Having said the above, why would you need to access the instance of the listener created?

**Comment by fzakaria** [comment]
@NiteshKant thanks. I think I just mis understood the use.

I have gotten the abstraction to work as expected however I'm looking for full round trip time for a request to get a sense of how long the average request takes.
Do you have some ideas on how to gather that ?

**Comment by fzakaria** [comment]
I believe it to be : requestProcessingTimes from looking at the code

**Comment by NiteshKant** [comment]
@fzakaria the [onRequestProcessingComplete](https://github.com/ReactiveX/RxNetty/blob/0.4.x/rxnetty/src/main/java/io/reactivex/netty/metrics/HttpClientMetricEventsListener.java#L117) callback on the `HttpClientMetricEventsListener` provides the time taken to process the request from submission to completion. It may or may not be useful depending on what latencies are looking at (client side queuing included or not). [0.5.x](https://github.com/ReactiveX/RxNetty/wiki/0.5.x-FAQs) provides more granular times, eg: time between headers written and response completion.

**Comment by NiteshKant** [comment]
I do not see any change which is required so closing.
