### ISSUE TITLE
HTTP client sends "Tranfer-Encoding: chunked" header with empty requests

### ISSUE THREAD

**Issue by bclozel** [ReactiveX/RxNetty#470]
Sending any requests with the HTTP client, without a "Content-Length" header set, results in sending a "Transfer-Encoding: chunked" header - even if the client is sending a GET request with no body at all.

This was previously addressed properly (see #119) but that part has been moved to [AbstractHttpConnectionBridge](https://github.com/ReactiveX/RxNetty/blob/f4c9034099cf1bd6cde0189abf3b41793621a8df/rxnetty-http/src/main/java/io/reactivex/netty/protocol/http/internal/AbstractHttpConnectionBridge.java#L100-L106).

This header should only appear if the "Content-Length" is not set and the request has a body.

**Comment by NiteshKant** [comment]
@bclozel does it violate the HTTP spec if the transfer-encoding is chunked but there is no content?

**Comment by bclozel** [comment]
I'm not 100% sure about this, since the spec sometimes refers to messages with "empty body", but I've [found this that at least suggests that a body should be present](https://tools.ietf.org/html/rfc7230#section-3.3):

> The presence of a message body in a request is signaled by a
>    Content-Length or Transfer-Encoding header field.  Request message
>    framing is independent of method semantics, even if the method does
>    not define any use for a message body.

The [next section](https://tools.ietf.org/html/rfc7230#section-3.3.3) does not strictly say that `Transfer-Encoding: chunked` requires a body, but there's still:

> If a Transfer-Encoding header field is present and the chunked
>        transfer coding (Section 4.1) is the final encoding, the message
>        body length is determined by reading and decoding the chunked
>        data until the transfer coding indicates the data is complete.

and 

> If this is a request message and none of the above are true, then
>        the message body length is zero (no message body is present).

Which both suggest that for an empty request, we should have either nothing or a `Content-Length: 0` header.

**Comment by NiteshKant** [comment]
As with any other RFC, I think two people interpret it differently :)

In order to make sure that we do not put `Transfer-Encoding: chunked` for empty bodies, we would have to delay writing headers until the content stream emits an item or terminates. Although possible, I think it does not achieve much benefit. A server that handles chunked encoding, must be able to handle such requests correctly if the request is correctly having the last chunk.

I would be interested in seeing if there are any servers that restricts such requests. I haven't seen any.

**Comment by bclozel** [comment]
I ran into this issue while testing the client with a [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver) instance.

**Comment by bclozel** [comment]
Some update on this.
The [RFC states](https://tools.ietf.org/html/rfc7230#section-3.3) that:

> The presence of a message body in a request is signaled by a
   Content-Length or Transfer-Encoding header field.  Request message
   framing is independent of method semantics, even if the method does
   not define any use for a message body.

So in that case, I guess the client should at least send a `0\r\n` body to send an empty body if nothing has been sent.

**Comment by NiteshKant** [comment]
@bclozel see #520 
We now have a case where sending empty chunk is an issue :)

**Comment by NiteshKant** [comment]
Fixed via #522

**Comment by ghost** [comment]
@NiteshKant Hello Nitesh, In transfer-encoding Chunked, which come first body or header?
