### ISSUE TITLE
[0.4.x] Disable auto-release buffers option forces to read content

### ISSUE THREAD

**Issue by Crystark** [ReactiveX/RxNetty#474]
Hi,

Here's a use case: When I add the `disableAutoReleaseBuffers` option to my server and i entrer a case where i don't consume the incoming content (e.g. 404 NOT FOUND) then the `ByteBuf` isn't released and thus creates a leak.

I would think that `.ignoreContent` would do the work but it seems it doesn't: you have to read the incoming `ByteBuf` and release it manually. This can be somewhat problematic cause using that option, rather than doing a `retain` where you want to use the `ByteBuf`, you need to do a `release` everywhere you do not want to use it.

And here's a couple questions while i'm at it:
- Does `ignoreContent` **have to** be called every time you do not use it ?
- Does the observable you return in the `RequestHandler` **have to** return an Observable issued by one of the `response` methods or would any observable do (even `Observable.empty`) ?

Thanks

**Comment by NiteshKant** [comment]
@Crystark Apologies for the delayed response. This sounds like a bug. One should not be forced to call `.ignoreContent()`. In absence of a subscriber, the buffer must be released with `disableAutoReleaseBuffers`. 

`RequestHadler` can return any `Observable` instance.

**Comment by NiteshKant** [comment]
Fixed via #497
