### ISSUE TITLE
Build error on travis CI when upgrade to 0.5.2-snapshot 

### ISSUE THREAD

**Issue by GrapeBaBa** [ReactiveX/RxNetty#478]
Hi,

I have a project using RxNetty for transportation. It is OK when using 0.5.0-snapshot, when i just change buiild.gradle to 0.5.2-snapshot test failed on travis CI. But it is OK in my local laptop. I am not sure what is possible issue.

Test Class:[https://github.com/GrapeBaBa/vineyard/blob/master/vineyard-grape/src/test/java/io/grapebaba/GrapeTest.java](url)

**Comment by NiteshKant** [comment]
There were issues with test, [0.5.2-rc.2](https://github.com/ReactiveX/RxNetty/releases/tag/v0.5.2-rc.2) fixes those issues.
