### ISSUE TITLE
Cannot find AbstractP2CStrategy.java using 0.5.2-snapshot 

### ISSUE THREAD

**Issue by GrapeBaBa** [ReactiveX/RxNetty#479]
Hi,

I cannot find the latest load balancer implementation in 0.5.2-snapshot.

**Comment by NiteshKant** [comment]
A snapshot has not been released after that change.

**Comment by NiteshKant** [comment]
Use [0.5.2-rc.2](https://github.com/ReactiveX/RxNetty/releases/tag/v0.5.2-rc.2) which is the latest release.
