### ISSUE TITLE
4.X Concat / Merge Execution Order

### ISSUE THREAD

**Issue by kennedyoliveira** [ReactiveX/RxNetty#483]
Hello everyone!

I got a doubt i don't know if it's pertinent to RxNetty or RxJava, but since it's about sending and receiving data over TCP i'll post here.

I'm learning Rx programming and loving it, already refactored some code in a production app and it's running more efficiently, so i'm start to write a implementation of Asterisk AMI Protocol using Rx.

The concept is a TCP socket connection with Asterisk server and the first step is, connect to the server, receive the asterisk information about the AMI Version, send a request for login, receive a response if it's succeed, after that the Asterisk server will start sending events, and you can interacting with it sending new actions.  

So far i wrote a little code to test, but it's not working as i expect, probably i'm misunderstanding something.

``` java
final RxClient<String, String> tcpClient = RxNetty.createTcpClient("192.168.1.244",
                                                                       5038,
                                                                       PipelineConfigurators.textOnlyConfigurator());

    final Observable<ObservableConnection<String, String>> connectionObservable = tcpClient.connect();

    connectionObservable.flatMap(c -> {
      final Observable<String> amiVersion = c.getInput().take(1);

      final Observable<String> events = Observable.concat(amiVersion, // first message received is the ami version
                                                          c.getInput() // split the message by delimiter Asterisk AMI Delimiter
                                                           .flatMap(s -> Observable.from(s.split("\r\n\r\n"))));
      return Observable.concat(
          // sends the login action
          c.writeAndFlush("Action: login\r\n" +
                              "Username: test\r\n" +
                              "Secret: test\r\n" +
                              "\r\n"),
          // gets the first event after i send the login, should be the resp?
          events.take(1).flatMap(r -> {
            System.out.println("Response: " + r);
            return Observable.empty();
          }));
    }).subscribe();
```

When i run this what happens is that it first write to asterisk and then it gets the first message being the asterisk version + the response from login, but since i'm using concat it shouldn't be gets the version, then sends the login action then gets the response?

By the way, whats the difference between concat and merge?

While writing the question, i guess i see what's going on here, maybe its executing first because on the second concat i first send the login action and then it subscribe to the events observable?

Another thing, i need to validate the version first and then write the second logic, how could i do that in a flat map?

I know it's a lot of questions, but i'm trying to learn RxNetty and i did not see too much material about it, so i hope you guys can help me understand better.

Thank you!

**Comment by NiteshKant** [comment]
> > maybe its executing first because on the second concat i first send the login action and then it subscribe to the events observable?

Correct, that is the reason it writes first.

> > i need to validate the version first and then write the second logic, how could i do that in a flat map?

Something like this,

``` java
connectionObservable.flatMap(c -> {
            final Observable<String> amiVersion = c.getInput().take(1).flatMap(s -> {
                if (s.equalsIgnoreCase("AmiVer")) {
                    return Observable.just(s);
                } else {
                    return Observable.error(new IllegalStateException("Unknown version"));
                }
            });
```

> >  whats the difference between concat and merge?

Docs on [reactivex](http://reactivex.io) are quiet useful for understanding the operators. [Concat](http://reactivex.io/documentation/operators/concat.html) and [Merge](http://reactivex.io/documentation/operators/merge.html) should give you an idea about the differences.

**Comment by kennedyoliveira** [comment]
Hi @NiteshKant, thanks for answering, and you cleared my doubt about this situation.
I'm new to react like a said, so i forgot was a Observable.error haha i guess it's ok for a newcomer.
By the way, the documentation was very clear about the difference, i read then so sleep that i didn't remember and asked instead of reading again.

```
The Merge operator is also similar. It combines the emissions of two or more Observables, but may interleave them, whereas Concat never interleaves the emissions from multiple Observables.
```

Another question, it's more about a pattern, considering the same context for asterisk ami, i need to do 2 things, receive the events, treat it and all, and the second is being able to send new actions so i'll get new responses, based on the documentation for the TcpClient connect 

```
Creates exactly one new connection for every subscription to the returned observable.
```

I will use only one connection, so i can subscribe to it just one time, i need to create all the logic from a single chain?

In the RxNetty tcp examples, all of this examples only show the logic being executed in a single chain, it's a limitation or there are other patterns to work?

I hope you can understand what i'm asking, i know my english isn't good.

Thank you very much!

**Comment by NiteshKant** [comment]
> > In the RxNetty tcp examples, all of this examples only show the logic being executed in a single chain, it's a limitation or there are other patterns to work?

An `ObservableConnection` allows multiple writes from different sources and RxNetty 0.4.x version also allow multiple input subscriptions. So, you can have multiple code paths using a connection. If you have a code example in an imperative style, I can suggest how it would be in with RxNetty.

**Comment by kennedyoliveira** [comment]
> If you have a code example in an imperative style, I can suggest how it would be in with RxNetty.

The code for that is a little complex and involves alot of code for managing actions and events, so i'm try to write a very simplified version to you. Thank you for proposing that, it's sure will help me to learn alot and probably other peoples with same doubts! :D

**Comment by kennedyoliveira** [comment]
Hey @NiteshKant!
I finally got some time to write a extreme simple code, i hope you can give me some advices on how to think reactive and should me some code.
I written some comments to make it clear somethings, it's very simple, and far from what i really want to implement, but i think if i managed to understand how to write it in reactive way, i can continue learning and writing the another parts.

Thank you very much!

```
package com.github.kennedyoliveira.asteriskjava.rx;

import java.io.*;
import java.net.Socket;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Kennedy Oliveira
 */
public class BlockingOldSchoolAmi {

  public static void main(String[] args) {
    try {
      final String host = "asterisk-host";
      final Socket socket = new Socket(host, 5038);

      final ReaderThread reader = new ReaderThread(socket);
      final Writer writer = new Writer(socket);

      // before starting the reader thread, we should first check the version and login
      final String amiVersion = reader.readVersion(); // should have a timeout

      // validate version
      if (!amiVersion.matches("valid ami pattern")) {
        throw new IllegalStateException("not a valid ami pattern");
      }

      String loginAction = "bla bla bla for login";

      // send the login action
      writer.sendAction(loginAction);
      final String loginResponse = reader.readNextEvent();// read a single event


      // if the login is ok, starts the reader thread so the events will be readed and dispatched
      if (isLoginOk(loginResponse)) {
        new Thread(reader).start();
      } else {
        throw new RuntimeException("Fail to login: " + loginResponse);
      }

      // listener that will listen to "dial" events, this event is triggered when something dial to a number
      final EventListener dialEventListener = new EventListener() {
        @Override
        public void onEvent(String event) {
          System.out.println("Dial event: " + event);
          // save in database that for example the ramal 100 dialed a number xxxxxxxxxxx
        }
      };

      reader.registerEventListener(dialEventListener);
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  /**
   * obviously should validate the login...
   */
  static boolean isLoginOk(String response) {
    return true;
  }

  static class ReaderThread implements Runnable {

    private final Socket socket;
    private final BufferedReader reader;
    private final EventDispatcher eventDispatcher;

    public ReaderThread(Socket socket) throws IOException {
      this.socket = socket;
      this.reader = new BufferedReader(new InputStreamReader(this.socket.getInputStream(), Charset.forName("UTF-8")));
      this.eventDispatcher = new EventDispatcher();
    }

    @Override
    public void run() {
      // extreme simple, and dumb implementation
      // not handling stop
      // not handling especial cases
      // some cases you have an event that is followed by many other
      // events that are part of the same "chain" and should be delivered as one,
      // but i'm not implementing for the sake of simplicity
      // and the event dispatcher should permit registering listeners to notify about the events
      while (true) {
        try {
          final String event = readNextEvent();
          eventDispatcher.dispatchEvent(event);
        } catch (IOException e) {
          e.printStackTrace();
        }
      }
    }

    /**
     * @return Should return an event object, but i'm returning a string for the sake of simplicity
     */
    public String readNextEvent() throws IOException {
      String line;
      StringBuilder sb = new StringBuilder();

      while (true) {
        line = reader.readLine();

        // if the line is only \r\n, means the end of an event, and it should be followed by another \r\n
        if ("\r\n".equals(line)) {
          final String nextLine = reader.readLine();

          // end of event
          if ("\r\n".equals(nextLine)) {
            break;
          }
        }

        sb.append(line);
      }

      return sb.toString();
    }

    /**
     * @return The first string, that will contains the version, this method should only be called once, and after
     * maybe return a cached result, i'm not implementing for the sake of simplicity
     */
    public String readVersion() throws IOException {
      return reader.readLine();
    }

    /**
     * should be thread safe
     */
    public void registerEventListener(EventListener listener) {
      this.eventDispatcher.registerEventListener(listener);
    }
  }

  /**
   * This class would be responsible to dispatch the events received through AMI, not implementing for the sake of
   * simplicity
   */
  static class EventDispatcher {
    private List<EventListener> listeners = new ArrayList<>();


    /**
     * should be thread safe
     */
    public void registerEventListener(EventListener listener) {
      this.listeners.add(listener);
    }

    /**
     * Handle the event in an other thread
     */
    public void dispatchEvent(String event) {
      // check if there are event listeners for this event
      // dispatch the events for the event listeners
    }
  }

  static class Writer {
    private Socket s;
    private BufferedWriter bf;

    public Writer(Socket s) throws IOException {
      this.s = s;
      this.bf = new BufferedWriter(new OutputStreamWriter(this.s.getOutputStream(), Charset.forName("UTF-8")));
    }

    // extreme simple implementation, the action parameter should be an action object
    // with all the needed information to build a action command
    public void sendAction(String action) throws IOException {
      this.bf.write(buildAction(action));
      this.bf.write("\r\n\r\n"); // marks the end of a command to asterisk
      this.bf.flush();
    }

    private String buildAction(String action) {
      return action;
    }
  }

  static class EventListener {
    // hadle the eent triggered
    public void onEvent(String event) {

    }
  }
}
```

**Comment by kennedyoliveira** [comment]
hey @NiteshKant, could you please, give me some hint on that? Thank you!
