### ISSUE TITLE
Multithread HttpServer best pratices

### ISSUE THREAD

**Issue by kennedyoliveira** [ReactiveX/RxNetty#485]
Hello everyone!

I'm using RxNetty to create a microservice that will responde to 4 ~ 6 specific resources to one application, and that microservice will be consumed by all the clients, like a central point of that resources, 1 of these resources if from a third party partner, and have some high latency, it vary from 800 ~ 1400 ms in my benchmarks to respond up to 250 ~ 500 req/s, my doubt is, what is the best way of running it async using an RxNetty HttpClient to make the request inside the HttpServer request handler and not block? 

Due to other resources being really easy to serve, they can run in the event loop, they will be cached in a redis instance most of the time so instantly lookup basically, just this one i wanna run in another thread and when it's ready, respond to the client that way not blocking the event loop and not using another thread for all request, just this one, as it will mostly be called seasonally, but i wanna understand how to write a efficient code in RxStyle.

I through about running a flatMap and subscribing in a Schedulers.io() on this specific resource call, but i'm not sure it's the best way, i did some simple benchmarks and noticed it got better throughput but  i don't fully understand subscribeOn and it's implication in the request handler chain.

Another doubt, i can use a singleton httpclient to make the call to this remote server? Since it will be a fixed ip, or creating the httpclient has little overhead that doesn't need to make it singleton and can create 1 for every request?

Lots of questions haha, but i hope someone can help me, thank you in advanced, a simplified code follows:

``` java
if (request.getHttpMethod().compareTo(HttpMethod.POST) == 0 && request.getPath().equals("/highdelayresource")) {
      return request.getContent()
                    .map(r -> r.toString(StandardCharsets.UTF_8))
                    .flatMap(c -> jsonService.fromJson(QrCodeConfig.class, c)) // converts the request payload to a especific pojo
                    .flatMap(c -> {
                      // make the call to the delayed remote serice
                      RxNetty.createHttpClient("remote_host", 443).submit(HttpClientRequest.createGet("path_for_resource")) // i can reuse the rxHttpClient?
                          .flatMap(resp -> resp.getContent().flatMap(c -> bufferedImageService.fromByteBuf(c))) // convert the bytebuff to a Observable<BufferedImage>
                          .subscribeOn(Schedulers.io())
                    })
                    .flatMap(bfImage -> {
                      try {
                        final ByteBuf buffer = response.getAllocator().ioBuffer();
                        final ByteBufOutputStream output = new ByteBufOutputStream(buffer); // is this the best way of geting the bytes of the image as a ByteBuf? I tested and it's working
                        ImageIO.write(bfImage, "png", output);
                        bfImage.flush();
                        response.getHeaders()
                                .set(HttpHeaders.CONTENT_LENGTH, String.valueOf(output.writtenBytes())) // in the simple example, it says that setting this property make rxNetty returns a single response instead of a chunked one, but for me everytime returns chunked
                                .set(HttpHeaders.CONTENT_TYPE, "image/png")
                                .set("in_event_loop", response.getChannel().eventLoop().inEventLoop());

                        response.write(buffer);
                      } catch (IOException e) {
                        return Observable.error(e);
                      }

                      return response.close(true); // when i set it to false, it hangs the response forever, why?
                    });
    } else {
      response.setStatus(HttpResponseStatus.NOT_FOUND);
      return response.close(true); // when i set it to false, it hangs the response forever, why?
    }
```

**Comment by NiteshKant** [comment]
If you are not explicitly blocking (eg: via `.toBlocking()`) nothing in RxNetty blocks. So, it is safe to execute an `HttpClient` request on the eventloop.

You mention that you are not comfortable running your third party service call in the eventloop because it is latent. Latency does not have an issue with asynchronous calls unless you block. So, I would not sweat running it on the eventloop.

**Comment by kennedyoliveira** [comment]
@NiteshKant , thank you for your feedback in all questions i asked haha, you are helping alot!
So, based on this answer and the #487, i only need to schedule the execution if when i consume the response content i block, in this case i will use observeOn to observe the emissions in another thread instead of the subscribeOn that i was using, it this correct?

Another thing about consuming the response in another thread, i remember reading about a problem with bytebufs being leaked or something, when consumed from another thread, there is any thing special i need to do in this case?

Thank you!
