### ISSUE TITLE
JavaAssist performance boost

### ISSUE THREAD

**Issue by kennedyoliveira** [ReactiveX/RxNetty#486]
When i start RxNetty i saw in the console `01:02:37.255 [main] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.`, does it applies to RxNetty? I saw some info that it helps improving performance for netty when it use some messageTo methods, i would like to know if it applies to RxNetty.

Thanks!

**Comment by NiteshKant** [comment]
@kennedyoliveira yes RxNetty will have the same performance characterstics as netty in absence of Javassist.

**Comment by kennedyoliveira** [comment]
@NiteshKant, but if i use Javassist the performance would be improved?

**Comment by NiteshKant** [comment]
Javassist is used by netty at a few places, if available. I have not come across any benchmarks of the comparisons between the two but it depends on your usage, so I would say it is worth to try it out.

**Comment by kennedyoliveira** [comment]
@NiteshKant, thanks, i will try to do a few benchmarks, if i see something interesting i'll share here

**Comment by NiteshKant** [comment]
Great, I am interested in hearing about what you find.
