### ISSUE TITLE
Test failures with RxJava 1.1.2

### ISSUE THREAD

**Issue by rstoyanchev** [ReactiveX/RxNetty#491]
The 0.5.x branch has some failures in the examples packages with RxJava 1.1.2. Here are a few failing tests although they do vary each time the tests are run:

```
LoadBalancingTest. testLoadBalancing
ServerSentEventsTest. testSse
MessagingTest. testMessaging
```

Failures are also present with RxJava 1.1.1 so possibly it goes back to that release. Are there plans to upgrade?

**Comment by NiteshKant** [comment]
I will take this up next week, once I am back in office.

**Comment by NiteshKant** [comment]
0.5.x is upgraded to 1.1.3 for the time being. I will upgrade to 1.1.4 later
