### ISSUE TITLE
Question: where is 0.4.x documentation?

### ISSUE THREAD

**Issue by chefhoobajoob** [ReactiveX/RxNetty#492]
New to RxNetty, want to use something stable for now, but can't find any documentation/examples on 0.4.x usage. Where should I look?

**Comment by jamesgorman2** [comment]
Have you looked on the 0.4.x branch?

If not, got to the root of the project and switch the branch to 0.4.x. The 0.4.x readme is here with links to the examples.

Direct links:
https://github.com/ReactiveX/RxNetty/tree/0.4.x
https://github.com/ReactiveX/RxNetty/tree/0.4.x/rxnetty-examples
