### ISSUE TITLE
Release 0.4.16?

### ISSUE THREAD

**Issue by mfulgo** [ReactiveX/RxNetty#493]
Hi @NiteshKant,

I was wondering if you'd be amenable to releasing 0.4.16 to at least get the memory leak fix for issue 466 published. (Since I suspect a fix for issue 474 will not be ready for a while.)

Thanks,
-Matt

**Comment by NiteshKant** [comment]
I am out of office and away from computer for a few weeks and back on 18th of this month. 
I will take the release as the first task once I am back. 

@brharrington @rspieldenner any chance we can set up release with Travis for 0.4.x branch too?

**Comment by brharrington** [comment]
> any chance we can set up release with Travis for 0.4.x branch too?

Back ported in #494

**Comment by NiteshKant** [comment]
@mfulgo I am still behind on closing the issue for this release. Hope to get it going this week.

**Comment by mfulgo** [comment]
Thanks for the update, Nitesh!

**Comment by bruceleexiaokan** [comment]
We are blocked by the bugs and waiting for a new release to fix memory and dispose bug. Looking forward to see the new version ASAP. Thanks a lot.

**Comment by NiteshKant** [comment]
@bruceleexiaokan @mfulgo I released 0.4.16 today.

**Comment by Crystark** [comment]
@NiteshKant I can see the release in the release section and on maven but I see no tags. Is that normal ?

Thanks alot for this release !

**Comment by NiteshKant** [comment]
@Crystark Actually the tag is there:

https://github.com/ReactiveX/RxNetty/tree/0.4.16

but I manually created it and missed the "v" prefix so it does not pop up to the top on the list 😵

**Comment by Crystark** [comment]
@NiteshKant indeed ! 

Thanks again for this version. We're currently testing it to see if it solves our leak problems. I'll let you know how it goes!
