### ISSUE TITLE
netty-transport-native-epoll dependency triggers warning

### ISSUE THREAD

**Issue by raphaelbrugier** [ReactiveX/RxNetty#496]
Hi,

I am running into an issue where having the netty-transport-native-epoll dependency in the classpath triggers a warning from the cassandra driver. Because the os specific binary is missing, which is legitimate.
see: jhipster/generator-jhipster#3428

I found this kind of problem has already been reported [here](https://groups.google.com/a/lists.datastax.com/d/msg/java-driver-user/QgwtAB7Mhn8/Yjc6XzNXF78J)
The fix is to either add the missing os specific lib or to have the library having a dependency to  netty-transport-native-epoll marks it as [optional](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) like done in the [cassandra-java-driver](https://github.com/datastax/java-driver/blob/2.1.6/driver-core/pom.xml#L77).

Is it possible to do this with RxNetty dependencies too?

The reasoning is that in all cases, the user already have to explicitly include the native binary to use the native support with RxNetty:

`compile group:"io.netty", name:"netty-transport-native-epoll", version:"${netty_version}", classifier: 'linux-x86_64'`

For reference, the dependency to netty-transport-native-epoll was introduced by #259

**Comment by NiteshKant** [comment]
@raphaelbrugier is "optional" supported by gradle? 
I am open to this idea and if you have a solution, feel free to send a PR!

**Comment by raphaelbrugier** [comment]
Hi @NiteshKant,

I assumed there "optional" is supported by gradle, and didn't check :) 
I'll verify and see if I can submit a PR.

For both the 0.4.x and 0.5.x branches I suppose?

**Comment by raphaelbrugier** [comment]
Well, I assumed too much.
optional support have been requested in gradle for a [long time](https://issues.gradle.org/browse/GRADLE-1749)
Gradle has recently (3 days ago! version 2.12) included a [compileOnly option](https://docs.gradle.org/current/release-notes#support-for-declaring-compile-time-only-dependencies-with-java-plugin) for the dependency which is similar to maven provided and should do the trick.

Unfortunately, when trying to upgrade the gradle version in this project, I ran into this bug: nebula-plugins/nebula-core#5

There is another gradle plugin to emulate the "optional" : [gradle-extra-configurations-plugin](https://github.com/nebula-plugins/gradle-extra-configurations-plugin)

It does the trick and the artifact published in my local maven repository show the dependency flagged as optional.

```
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-epoll</artifactId>
      <version>4.1.0.Beta7</version>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>

```

My only concern, is that the library was already in a `runtime scope`, so I'm not sure of the effect of the optional flag in that case.
Are you familiar with this already?

**Comment by raphaelbrugier** [comment]
Hi,

I was able to run the `HttpLoadBalancingClient` example in a separate project depending on the new pom and it works fine.

Here is the dependency graph with maven on this sample: 

```
mvn dependency:tree                  
[MVNVM] Using maven: 3.3.9
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building testRxNetty 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ testRxNetty ---
[INFO] com.rbrugier:testRxNetty:jar:1.0-SNAPSHOT
[INFO] +- io.reactivex:rxnetty-common:jar:0.5.2-SNAPSHOT:compile
[INFO] |  +- org.openjdk.jmh:jmh-generator-annprocess:jar:1.11.2:runtime
[INFO] |  +- org.openjdk.jmh:jmh-core:jar:1.11.2:runtime
[INFO] |  |  +- net.sf.jopt-simple:jopt-simple:jar:4.6:runtime
[INFO] |  |  \- org.apache.commons:commons-math3:jar:3.2:runtime
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] +- io.reactivex:rxnetty-http:jar:0.5.2-SNAPSHOT:compile
[INFO] +- io.reactivex:rxnetty-spectator-http:jar:0.5.2-SNAPSHOT:compile
[INFO] |  +- io.reactivex:rxnetty-spectator-tcp:jar:0.5.2-SNAPSHOT:runtime
[INFO] |  |  \- com.netflix.numerus:numerus:jar:1.1:runtime
[INFO] |  \- com.netflix.spectator:spectator-api:jar:0.14.2:runtime
[INFO] +- io.reactivex:rxnetty-tcp:jar:0.5.2-SNAPSHOT:compile
[INFO] +- io.reactivex:rxjava:jar:1.1.0:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.6:compile
[INFO] |  \- log4j:log4j:jar:1.2.17:compile
[INFO] +- org.mockito:mockito-all:jar:1.9.5:compile
[INFO] +- io.netty:netty-handler:jar:4.1.0.Beta7:compile
[INFO] |  +- io.netty:netty-buffer:jar:4.1.0.Beta7:compile
[INFO] |  |  \- io.netty:netty-common:jar:4.1.0.Beta7:compile
[INFO] |  +- io.netty:netty-transport:jar:4.1.0.Beta7:compile
[INFO] |  |  \- io.netty:netty-resolver:jar:4.1.0.Beta7:compile
[INFO] |  \- io.netty:netty-codec:jar:4.1.0.Beta7:compile
[INFO] \- io.netty:netty-codec-http:jar:4.1.0.Beta7:compile
```

I'll prepare a PR
