### ISSUE TITLE
Public vs Private APIs

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxNetty#5]
Right now we don't have the public APIs correctly exposed. For example, we have some classes hiding in `rx.netty.impl` that are actually part of the public API so they should be inside an `impl` package. The `ObservableHttpResponse` object is deep inside a `protocol` package that is definitely full of private objects.

The `RxNetty` class is definitely the entry point, and anything it exposes should also become part of the `rx.netty` package structure I think, or something other public package off of `rx.netty`. The `rx.netty.impl` and `rx.netty.protocol` packages should be filtered from the public Javadoc and treated as internal implementation details I think.

**Comment by NiteshKant** [comment]
After this refactoring: https://github.com/Netflix/RxNetty/pull/19

The following is the package structure:

```
└── io
    └── reactivex
        └── netty
            ├── client
            ├── pipeline
            ├── protocol
            │   ├── http
            │   │   └── sse
            │   └── text
            │       └── sse
            └── server
```

With the first level package: io.reactivex.netty only containing RxNetty and ObservableConnection classes.

The general classes people have to interact with are:

1) RxNetty: Easy entrypoint for creating simple clients & server.
2) RxServer or protocol specific extensions of the same: For various protocol servers. There are builders for every server.
3) RxClient or protocol specific extensions of the same: For various protocol clients. There are builders for every client. 
4) PipelineConfigurators: Factory class for creating various netty pipelines, to be used with RxServer/RxClient.

Does this suffice? If yes, I will close this issue.
