### ISSUE TITLE
jmh-core dependency: what is it for?

### ISSUE THREAD

**Issue by graemerocher** [ReactiveX/RxNetty#501]
I've been looking at the source of the project and trying to understand the dependency graph and so on. Can someone explain what the `jmh-core` and `jmh-generator-annprocess` dependencies are for? I cannot find any reference to these libraries in the codebase. Are they transitive dependencies needed by some library? 

I commented out the dependencies and ran `gradle check` and all tests pass except one in the `rxnetty-tcp` subproject, but that test fails regardless of the presence of the dependency so I think the failure is unrelated.

Reference: https://github.com/ReactiveX/RxNetty/blob/0.5.x/build.gradle#L40

**Comment by NiteshKant** [comment]
It was added for perf tests but the tests never made it in, so it can be removed.
