### ISSUE TITLE
Race condition between connection creation and Observable/Pipeline creation

### ISSUE THREAD

**Issue by nithril** [ReactiveX/RxNetty#505]
Hello,

I  start `HelloWorldServer` and I run `HelloWorldClient` multiple time. Sometime `HelloWorldClient` hangs waiting for the response. 

A netstat shows the connection is established but the request is not sent. When I debug the whole thing, I seems there is a race condition when establishing the connection

To reproduce the issue `HelloWorldClient` must be executed in debug mode. IDE is configured to only stop the current thread at breakpoint. Set a breakpoint at `io.reactivex.netty.protocol.tcp.client.TcpClientImpl.TerminalConnectionProvider#newConnectionRequest` [L274](https://github.com/ReactiveX/RxNetty/blob/57f8a34709fca5e7a997c58a8143dfb2c85d47cf/rxnetty-tcp/src/main/java/io/reactivex/netty/protocol/tcp/client/TcpClientImpl.java#L274) and launch  `HelloWorldClient`  in debug mode.
1. Step over L274 `final ChannelFuture cf = bootstrap.connect(host.getHost());`.
2. Step over L275 `s.add(Subscriptions.create(new Action0()...`
3. Step over L283 `cf.addListener(new ChannelFutureListener() {`. 

Connection is started by `1.`,  Netty setup the connection in its event loop thread. `ChannelPromise` listeners are called,  `pipeline().fireChannelActive();` is called.
RxNetty setup the Future completion listener on `3.`. This listener setup the `ChannelPipeline` with the handler to write the request. Because the connection has already been initialized and the pipeline has already fired the `fireChannelActive`, the pipeline is setuped but the added handlers will not be called for this request and thus the request will not be called.

Hope it will help to take down this issue

**Comment by NiteshKant** [comment]
Thanks @nithril for the detailed analysis of the issue.

I have put in a fix for the issue and it looks like all travis failures were due to this race! Here is the relevant PR #504

**Comment by nithril** [comment]
Thanks for the fix
