### ISSUE TITLE
RxNetty server hangs if request content subscriber does not unsubscribe

### ISSUE THREAD

**Issue by rstoyanchev** [ReactiveX/RxNetty#509]
When using [RxJava1ObservableConverter](https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/core/converter/RxJava1ObservableConverter.java) from the Reactor project the server hangs when request input is read but no response output is written. 

This is because unlike the official Reactive Streams / RxJava bridge, the alternative from Reactor does not call cancel (disallowed by spec rules) and as a result an "active" request content subscriber remains. So when `request.dispose()` is called `HttpServerToConnectionBridge` finds this an "active" subscriber and fires an event that then gets dropped.

[See a discussion](https://github.com/reactor/reactor/issues/603#issuecomment-207375166) on this with @akarnokd who also had a look and suggested a possible fix. 

I don't fully understand the implications myself  but I can confirm that the suggested fix, which is to call `super.userEventTriggered` instead of `ctx.fireUserEventTriggered` does work. I'm happy to test any other alternative change.

**Comment by NiteshKant** [comment]
@rstoyanchev and @akarnokd thanks for digging into this.

Irrespective of this issue, the call to `ctx.fireUserEventTriggered` is wrong in the class in question. As @akarnokd pointed, it should be changed to `super.userEventTriggered`.

For this issue, I am a bit confused about why this fix will work. As you have mentioned that the subscriber does not call unsubscribe and this code is executed only when the subscriber unsubscribes (as it is an action for `Subscriber.add()`). So, the two things seems unrelated or I misunderstood the issue?

Anyways, i will go ahead and make the change to call `super.userEventTriggered`.

**Comment by rstoyanchev** [comment]
I think this code is executed also as a result of `request.dispose()`.

**Comment by NiteshKant** [comment]
Correct, `dispose()` will subscribe to the content, which will be enqueued in the `pendingContentSubs` queue. The code in question though will only be called on `unsubscribe` which is what confuses me as to why it will help as for the case in question, no one unsubscribes.

**Comment by NiteshKant** [comment]
FYI #510 uses the fix as suggested here.

**Comment by rstoyanchev** [comment]
The most recent snapshot [I see here](https://oss.jfrog.org/artifactory/libs-snapshot/io/reactivex/rxnetty-http/0.5.2-SNAPSHOT/) is from 5/23. As soon as there is one that includes the fix I will verify it.

As for what actually happens, here is a stack trace that may help:
![image](https://cloud.githubusercontent.com/assets/401908/15696680/dfbaad3c-2780-11e6-9a13-0d2ec61247ca.png)

This is based on the [modified Hello World sample](https://github.com/rstoyanchev/RxNetty/tree/hanging-issue) I had created previously that demonstrates the issue. It might be easier if you run the sample to see how it gets to that point.

**Comment by NiteshKant** [comment]
@rstoyanchev the latest snapshot contains this fix.

Yeah that stacktrace is for RxJava subscribers that cleanly unsubscribes. My question is that if the content subscriber does not unsubscribe, then why does this fix will help. Anyways, try out the latest snapshot to see if the issue is fixed. I will keep this one open till I hear from you.

**Comment by rstoyanchev** [comment]
@NiteshKant thanks for re-opening. I can confirm the fix does work.

**Comment by NiteshKant** [comment]
Thanks!
