### ISSUE TITLE
chunked encoding header is added prematurely 

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#51]
In `HttpRequest.withContent(T content)`, it adds `Transfer-encoding: chunked` header if the content length is not set. However, content length can be set later with `withHeader()` method since we allow arbitrary sequence of the `with...()` calls in the builder.

**Comment by NiteshKant** [comment]
Good catch!
The transfer-encoding header or content length must be added before sending the request not at creation of the request.
