### ISSUE TITLE
Callbacks for custom http log

### ISSUE THREAD

**Issue by leslie-leder** [ReactiveX/RxNetty#514]
With version 0.5.2.I can't figure out how to add all required callbacks in a single step to the HttpClientRequest in order to write a complete http log in a custom format. 

I think about a function _HttpClientRequest<I,O> => HttpClientRequest<I,O>_ wherein I could add all callbacks in order to get all information about the effective _HttpClientRequest_, _HttpClientResponse_ pair. So I could log  uri, method, version, headers, in data, status, out header, out data, ...
Could be thought like a _javax.servlet. FilterChain_ without the transformation capabilities, just for read.

Currently I create a specific Logger class where I pass the fully created HttpClientRequest into the constructor. Otherwise I do not get all header attributes.

For  content logging I use _transformContent, transformResponseContent_ , so I could log without having the actual input stream.

For response logging I use the flatMap operation after the HttpClientRequest.writeContent invocation.

**Comment by NiteshKant** [comment]
Interceptors are a good way of intercepting(logging in your case) request/responses on a client. [rxnetty-examples](https://github.com/ReactiveX/RxNetty/tree/0.5.x/rxnetty-examples) contains examples for interceptors, [here](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/interceptors/simple/InterceptingClient.java) and  [here](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/interceptors/transformation/InterceptingClient.java)

Let me know if that isn't what you are looking for.

**Comment by leslie-leder** [comment]
I've tried to use the _InterceptingHttpClient.intercept_ method in order to achieve a similar behavior like _HttpClient.enableWireLogging_.

But the inner _RequestProvider.createRequest_ method expose only http- version, method and uri. There are no request header attributes available. 

With _transformContent_ I do log the request and with _transformResponseContent_ I get the response data. 

But where do I get the response headers and status from?

If I need to log header and status info there are at least two additional places where I need to add my logger to. 
One is right after the _HttpClientRequest_ is fully configured, in order to capture the request meta-data.
The other is in _Observable[HttpClientResponse].onEach_ which could be the _HttpClientRequest_ itself or the Observable created by _HttpClientRequest.writeContent_, in order to capture response meta-data/status.

I see currently no way to create an HttpClient with my custom logger pre-configured in a central place, so the business code does not need to care about logging at all.  

What I'm looking for is a central place where I can capture all request/response related data, meta-data and errors in the client.

**Comment by NiteshKant** [comment]
@leslie-leder I think having a netty channel handler for this log will be much easier (and pluggable) than using interceptors. You may find the following handler useful:

``` java
    private static class AccessLogger extends ChannelDuplexHandler {

        /*Http Client does not support pipelining, so one record is sufficient.*/
        private LogRecord record = new LogRecord();

        @Override
        public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
            if (msg instanceof HttpResponse) {
                HttpResponse resp = (HttpResponse) msg;
                record.recordResponse(resp);
            } else if (msg instanceof LastHttpContent) {
                record.log();
            }
            super.channelRead(ctx, msg);
        }

        @Override
        public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise)
                throws Exception {
            if (msg instanceof HttpRequest) {
                record = new LogRecord();
                HttpRequest req = (HttpRequest) msg;
                record.recordRequest(req);
            } else if (msg instanceof HttpContent) {
                record.nextContent();
            } else if (msg instanceof LastHttpContent) {
                record.requestComplete();
            }
            super.write(ctx, msg, promise);
        }

        private static class LogRecord {

            private String uri;
            private HttpMethod method;
            private String userAgent;
            private long startTime;
            private long responseTime;
            private int responseCode;

            public void recordRequest(HttpRequest req) {
                uri = req.uri();
                method = req.method();
                userAgent = req.headers().get(HttpHeaderNames.USER_AGENT);
                startTime = System.currentTimeMillis();
            }

            public void nextContent() {
                // No op
            }

            public void requestComplete() {
                // No Op
            }

            public void recordResponse(HttpResponse resp) {
                responseCode = resp.status().code();
                responseTime = System.currentTimeMillis() - startTime;
            }

            public void log() {
                System.out.println(this);
            }

            @Override
            public String toString() {
                String sb = "LogRecord{" + "uri='" + uri + '\'' +
                            ", method=" + method +
                            ", userAgent='" + userAgent + '\'' +
                            ", startTime=" + startTime +
                            ", responseTime=" + responseTime +
                            ", responseCode=" + responseCode +
                            '}';
                return sb;
            }
        }
    }
```

You can add this handle to the client as follows:

``` java
        HttpClient.newClient(serverAddress)
                  .<ByteBuf, ByteBuf>addChannelHandlerLast("access-log", () -> new AccessLogger())
```

Apologies for suggesting the wrong direction initially.

**Comment by leslie-leder** [comment]
@NiteshKant this is exactly what I was looking for. Thanks a lot for this detailed foolproof example.

**Comment by NiteshKant** [comment]
No worries, @leslie-leder I will close this issue now.

**Comment by RikkiGibson** [comment]
Is there a reason that RxNetty interceptors don't provide access to the response code or headers?

**Comment by jamesgorman2** [comment]
@RikkiGibson I don't have an answer, but would like to know if you have a use case in mind?

**Comment by RikkiGibson** [comment]
Actually, I think my use case might be particularly tricky with Netty/RxNetty. A response may come back from our REST API which indicates that a request should be tried again on a different host, given by a certain response header. It's semantically different than just an HTTP redirect response code, I think. So what I would want is an interceptor that can inspect a response status code and headers in order to decide that it should retry the request to a different host.

My team probably has other instances where having access to the response status code and headers would be useful, but that's the biggest one that's seemed daunting to solve with just a ChannelHandler.

**Comment by jamesgorman2** [comment]
You can use Observable composition to do most, if not all, of what you want. A two host call could look like:

```java
    HttpClient.newClient("host1", 443)
      .createGet("/")
      .flatMap(
        response ->
          requiresRedirect(response) ?
            HttpClient.newClient("host2", 443)
              .createGet("/")
              .flatMap(HttpClientResponse::getContent) :
            response.getContent()         
      )
      .compose(parseContent);
```

Personally I don't like the `ChannelHandler` way of manipulating byte streams since it's not truely type safe and breaks the Rx style. Internally we do things like this for preference, and only use the ChannelHandlers for monitoring.

**Comment by RikkiGibson** [comment]
Thanks for the suggestion and the example code.
