### ISSUE TITLE
Facilitate query parameter building for HttpRequest 

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#52]
Since we are providing our new HttpRequest abstraction, it will be convenient to add APIs that helps users to build the URI with query parameters and handle the encoding.

**Comment by NiteshKant** [comment]
The HttpRequest creation takes a URI which is expected to be created before hand. Is there any specific benefit providing a URI without query parameters and then giving a way to append them?

If we do, the code becomes unnecessarily complex to find out whether the URI already contains query params or not, which entails parsing the URI. As opposed to the user adding then before hand.

**Comment by NiteshKant** [comment]
Had a chat with Allen. There are cases where in someone wants to build a URI incrementally, however, the use case can be handled outside the HttpRequest class using lets say a URIBuilder which gives you various options of encoding, adding Query Parameters etc. Once it gets to HttpRequest, the URI is immutable.

**Comment by NiteshKant** [comment]
Won't fix this. URI is built and sent to the HTTP client.
