### ISSUE TITLE
Example project in 0.5.x still points to code from 0.4.x

### ISSUE THREAD

**Issue by tebeco** [ReactiveX/RxNetty#532]
Hi,

I've just discovered this project and also that some ".md" in example project says to use code like :
RxNetty.createHttpServer(...)

Fact is, it took me 1 hours to understand that there's 2 branch here ... and the fact that each branch hold non compliant API Version
And also that the "0.5.x" does not have history from the 0.4.x branch

It's not critical but I guess that for new comer it might be good to have the sample "md" file poiting to the right branch of code ^^

cheers :)

**Comment by NiteshKant** [comment]
Can you point me to the links that are broken or better still want to send a PR for the fix!!

**Comment by tebeco** [comment]
I would love to do a PR but as I said i'm discovering Netty so i don't know the API yet

If you search in *.md for "createHttpServer" thos api does not exist anymore
And I think the code next to these lines also points to 0.4
