### ISSUE TITLE
RxNetty SSL configuration

### ISSUE THREAD

**Issue by groodt** [ReactiveX/RxNetty#548]
It seems that for RxNetty, I have to manually specify if the client should use SSL. Something like the snippet below for 0.4.x

```
        CompositeHttpClientBuilder<ByteBuf, ByteBuf> clientBuilder = new CompositeHttpClientBuilder<>();

        if (!env.contains("local")) {
            clientBuilder.withSslEngineFactory(new DefaultSSLEngineFactory()); // SSL only enabled for non-local
        }

        return clientBuilder.build();
```

I also had to create a class DefaultSSLEngineFactory like this:

```
    private static class DefaultSSLEngineFactory implements SSLEngineFactory {

        private final SslContext sslCtx;

        private DefaultSSLEngineFactory() {
            try {
                sslCtx = SslContextBuilder.forClient().build();
            } catch (SSLException e) {
                throw new IllegalStateException("Failed to create default SSL context", e);
            }
        }

        @Override
        public SSLEngine createSSLEngine(ByteBufAllocator allocator) {
            return sslCtx.newEngine(allocator);
        }
    }
```

For ease of use, this seems a little cumbersome in my opinion. Is there a specific reason for it? Coming from using HC Apache or AsyncHttpClient/async-http-client, this seems like a lot of extra work.

I imagine for many client use-cases, they will want to communicate over SSL/TLS in Production environments, and use non-SSL/TLS for localhost, CI and/or integration test environments.

It seems that if I enable SSL as above for localhost, then communication over http:// doesn't work, so I have to explicitly unwire it for the clients on localhost.

I'm asking if I am doing something wrong, or if there is a strong rationale for this?

**Comment by NiteshKant** [comment]
> > > For ease of use, this seems a little cumbersome in my opinion. Is there a specific reason for it? 

0.5.x makes the API "better" by introducing `.secure()` and [`.unsafeSecure()`](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/secure/SecureHelloWorldClient.java#L78) methods on the client. For quick testing `unsafeSecure()` is pretty handy as it uses a `trust-all` factory. 
For actual production code, it requires netty's `SSLCodec` or `SSLEngine` which I think is the norm (?).

> > > I imagine for many client use-cases, they will want to communicate over SSL/TLS in Production environments, and use non-SSL/TLS for localhost, CI and/or integration test environments.

Indeed, for such cases, one would typically configure the client conditionally. As mentioned above, 0.5.x makes this a bit easier.

> > > I'm asking if I am doing something wrong, or if there is a strong rationale for this?

Providing a way to infer SSL or otherwise from the URL makes the implementation more complex and appears to provide a "magical way" of handling SSL. It also results in runtime failures if SSL is not configured. Having the client configured for SSL explicitly makes it more explicit and safe IMO.

**Comment by groodt** [comment]
Thanks @NiteshKant The API is indeed friendlier in 0.5.x. I have figured it out now, but it is difficult to use if you are relatively new to the internals of Netty like me. An example that uses .unsafeSecure() is fine, but how to connect to a 'real' SSL server in the wild?

Something like this?

```
            SSLEngine engine = SSLContext.getInstance("TLS").createSSLEngine();
            HttpClient.newClient("host", 443).secure(engine).createGet("/path");
```

And am I correct in thinking that if using SSL, then it is impossible to communicate via plaintext with the same client. So there is no way for a client to make a plain-text request and then redirect to SSL?

**Comment by NiteshKant** [comment]
> > > And am I correct in thinking that if using SSL, then it is impossible to communicate via plaintext with the same client.

Correct, there is no way to use the same client with SSL and plain-text.

**Comment by groodt** [comment]
Ok, so no clients with dual SSL and plain-text. Got it.

Is the example above an appropriate way to setup .secure()? It seems a little dangerous to make the .unsafeSecure() so easy and not having any documents or convenience methods for doing .secure() as well. I appreciate there are complexities involved with JSSE, but is this a quick-start way to use SSL that would work for most users?

```
SSLContext.getDefault().createSSLEngine()
```

If so, would it make sense to add a .secure() or .defaultSecure() that does this inside netty so that it is easy to get setup using SSL quickly?

**Comment by NiteshKant** [comment]
@groodt I am no expert in SSL and hence do not want to give an advice on it. 
IMO, `SSLContext.getDefault().createSSLEngine()` is not sufficient for production use and hence it does not make sense to be put as the default way to configure SSL. I would rather have a user understand SSL before configuring it and make a conscious decision to use the default configurations.

**Comment by groodt** [comment]
@NiteshKant It's a fair enough argument. I agree that the opportunity for experts to configure SSL specifics themselves should be in place, but I think that if there isn't an example or wiki or convenience methods that 'setup the secure and basic' defaults, then I worry that people will either choose another library that is easier to bootstrap or even worse, do something terrible like .unsafeSecure() out of frustration. While this isn't your problem directly, I would urge you to shift users of your library into doing the 'right thing' in an easy way. :)

**Comment by NiteshKant** [comment]
@groodt fair point!

Do you want to add an example on how to use `.secure()`?

**Comment by groodt** [comment]
Sure thing @NiteshKant I'll prepare something and create a PR

**Comment by groodt** [comment]
I've created a PR here https://github.com/ReactiveX/RxNetty/pull/553
