### ISSUE TITLE
0.5.x roadmap or expected RC version

### ISSUE THREAD

**Issue by groodt** [ReactiveX/RxNetty#550]
I'm wondering if there is an expected release schedule for RxNetty 0.5.x? I can't seem to find any artifacts but Snapshot artifacts and the incorrectly released 0.5.x artifacts from the 0.4.x branch.

**Comment by NiteshKant** [comment]
@groodt 0.5.x has release candidates published to maven, here is the last RC:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.reactivex%22%20AND%20v%3A%220.5.2-rc.4%22

You can find the release details for this and future releases on [this page](https://github.com/ReactiveX/RxNetty/releases)

**Comment by groodt** [comment]
Thanks very much @NiteshKant I didn't see that before. Any goal or indicator for the 0.5.x final release?

**Comment by NiteshKant** [comment]
> >  Any goal or indicator for the 0.5.x final release?

Unfortunately not yet. We are testing this inside Netflix currently.

**Comment by groodt** [comment]
No prob @NiteshKant The 0.5.2-rc.4 seems to be working really well! You're doing great work. I'll keep an eye on the [releases page](https://github.com/ReactiveX/RxNetty/releases)
