### ISSUE TITLE
Check for SSE stream does not take charset into account

### ISSUE THREAD

**Issue by rhart** [ReactiveX/RxNetty#552]
The check for SSE content type in `HttpClientResponseImpl` does not take into account that a charset may also be present in the header.  A content type of `text/event-stream;charset=UTF-8` results in an `IllegalStateException`.

https://github.com/ReactiveX/RxNetty/blob/1d6eb41994b70098fe0c2ec68b5ce1e650951e69/rxnetty-http/src/main/java/io/reactivex/netty/protocol/http/client/internal/HttpClientResponseImpl.java#L258

**Comment by NiteshKant** [comment]
@rhart you are correct. It should probably be doing a `startsWith` check. Do you want to send a PR?

**Comment by rhart** [comment]
Yeah, sure 👍
