### ISSUE TITLE
SSE fails for Content-Type with charset defined: text/event-stream;charset=UTF-8

### ISSUE THREAD

**Issue by leslie-leder** [ReactiveX/RxNetty#556]
with HttpClient version 0.5.2-rc.4 I get an IllegalArgumentException for SSE with **charset** set to any value.

The corresponding code the checks for "text/event-stream" without tolerating **charset** property added like so:

**Content-Type**
`Content-Type: text/event-stream;charset=UTF-8`

**HttpClientResponseImpl**

``` @Override
    public ContentSource<ServerSentEvent> getContentAsServerSentEvents() {
        if (containsHeader(CONTENT_TYPE, "text/event-stream", false)) {
          ...
        }

        return new ContentSource<>(new IllegalStateException("Response is not a server sent event response."));
    }
```

**Comment by rhart** [comment]
@leslie-leder see #552

**Comment by NiteshKant** [comment]
Thanks @rhart 

@leslie-leder I will close this one as a duplicate.
