### ISSUE TITLE
Get response content of HttpClientRequest

### ISSUE THREAD

**Issue by tdittmann** [ReactiveX/RxNetty#559]
Hi,
how can i get the content of my request with rxnetty? I use the following code

```
public byte[] doCall(...) {
LoadBalancingHttpClient client = RibbonTransport.newHttpClient(loadBalancer);
HttpClientRequest request = HttpClientRequest
                .createPost("/finances")
                .withHeader("Content-Type", "application/json");
client.submit(request);

return ...;
}
```

I tried many things like _submit(request).subscribe()_, _httpClientResponse.getContent()_, ... 
But it does not work... my server returns a byte array, how can i save this in a local variable?

**Comment by jamesgorman2** [comment]
If you just want byte data without the NIO/observables you're probably better off using ribbon-httpclient. If you want rxnetty under the hood, this will return the bytes wrapped in an observable. To escape the Observable use `doCall(...).toBlocking().first()`.

``` java
public Observable<byte[]> doCall(...) {
  LoadBalancingHttpClient client = RibbonTransport.newHttpClient(loadBalancer);
  HttpClientRequest request = HttpClientRequest
                .createPost("/finances")
                .withHeader("Content-Type", "application/json");
  return client.submit(request)
    .flatMap(response -> response.getContent())
    // get the bytes out
    .map(buf -> {
      byte[] bytes = new byte[buf.readableBytes()];
      buf.readBytes(bytes);
      return bytes;
    })
    // collect into a single array since the data might be chunked
    .reduce(
      new byte[0],
      (acc, bytes) -> {
        byte[] result = new byte[acc.length + bytes.length];
        System.arraycopy(acc, 0, combined, 0, acc.length);
        System.arraycopy(bytes, 0, combined, acc.length, bytes.length);
        return result;
      }
    );
}
```

**Comment by tdittmann** [comment]
Thanks. I always used the RestClient from Ribbon but it is deprecated :(
I hope LoadBalancingHttpClient is the "right" way to replace the deprecated RestClient... the documentation is not updated yet and i only found this approach
€dit: can be closed ;)

**Comment by tdittmann** [comment]
Another question: how can i get the response code? i tried it like in your example with flatmap and map, but it does not work :(

**Comment by jamesgorman2** [comment]
For this you have to make sure your lambdas are properly nested to capture the response code and content together (each lambda can see the params, variables and args of the lambdas, method and class above). Compared to the previous version, the action all happens inside `responseObservable.flatMap(...)`, which gives us access to the response inside. Once we get to `bytesObservable.map(...)`, the lambda can see the raw byte array (as argument) and the raw response (since it is the argument to a parent closure).

If you haven't done a bunch of RX/function programming it a can take a bit to get you head around the layering needed.

``` java
Observable<byte[]> asBytes(Observable<ByteBuf> oBuf) {
  return oBuf
    .map(buf -> {
      byte[] bytes = new byte[buf.readableBytes()];
      buf.readBytes(bytes);
      return bytes;
    })
    .reduce(
      new byte[0],
      (acc, bytes) -> {
        byte[] result = new byte[acc.length + bytes.length];
        System.arraycopy(acc, 0, combined, 0, acc.length);
        System.arraycopy(bytes, 0, combined, acc.length, bytes.length);
        return result;
      }
    );
}

public Observable<ResponseHolder> doCall(...) {
  LoadBalancingHttpClient client = RibbonTransport.newHttpClient(loadBalancer);
  HttpClientRequest request = HttpClientRequest
                .createPost("/finances")
                .withHeader("Content-Type", "application/json");
  return client.submit(request) // responseObservable
    .flatMap(response ->
      response.getContent()
        .compose(this::asBytes) // bytesObservable
        .map(bytes -> new ResponseHolder(response.getStatus().code(), bytes))
    );
}
```

**Comment by tdittmann** [comment]
Thanks, worked :)
