### ISSUE TITLE
RxJava version

### ISSUE THREAD

**Issue by kennedyoliveira** [ReactiveX/RxNetty#561]
Hi, i would like to know if there's any problem updating the RxJava version RxNetty is using, because, currently it's set to 1.0.+, but the last 1.x version is 1.2.2, i tried to fetch the project, update and run the tests but it's failing, so i don't know if is because of this version, since it's failing with default version too, but different test, so i guess could be, but not sure, didn't dig to see.

Anyway, is there any plan to update the version to latest 1.x? What about the new 2.x?

Thank you.

**Comment by kennedyoliveira** [comment]
I just deleted my local source copy, pulled again and tests it's passing all test for the RxJava 1.2.2, so probably was something wrong with my local source.

**Comment by NiteshKant** [comment]
@kennedyoliveira If you have bandwidth trying moving RxNetty to RxJava 2.x, I am happy to see a PR. Currently, I do not have bandwidth to do that

**Comment by kennedyoliveira** [comment]
@NiteshKant i would like to help, but i don't know if i can, i don't know the architecture of RxNetty, and won't be able to implement on RxJava 2.x unless i have some help and explanations about the core/internals.

**Comment by jamesgorman2** [comment]
Just put in #563 and #562 for 0.4.x and 0.5.x to RxJava 1.2.+

@NiteshKant I missed RxJava 2 going stable. I've still got to grok the API changes but want to re-release some of my stuff on the next version. I'll see if I can have a look RxNetty too you want a new issue for that upgrade since it'll be fairly major?

**Comment by NiteshKant** [comment]
@jamesgorman2 yes lets have a separate issue and I can put my thoughts on the issue!

Let me close this one.
