### ISSUE TITLE
Question regarding RequestCorrelator and Rxnetty 0.4

### ISSUE THREAD

**Issue by jaume-pinyol** [ReactiveX/RxNetty#564]
Hi,

I have an issue regarding RequestCorrelator and I don't know if I'm doing something wrong or I've configured it wrongly. The case is that inside the application code (The router or handler) I can't have access to the request id(I could always get it from the request, but I think that's why the request correlator is for...). 
When I try to do:
```java
RxContexts.DEFAULT_CORRELATOR.getRequestIdForClientRequest()
````
It is always null, I've debugged the code and when there is a new request the id is catched|generated properly in: 

```
https://github.com/ReactiveX/RxNetty/blob/0.4.x/rxnetty-contexts/src/main/java/io/reactivex/netty/contexts/http/HttpRequestIdProvider.java#L85
```

This is how I start the server
```
 HttpServerBuilder<ByteBuf, ByteBuf> serverBuilder = RxContexts
                .newHttpServerBuilder(port, requestHandlerWrapper, RxContexts.DEFAULT_CORRELATOR)
                .withRequestProcessingThreads(requestProcessingThreads);
```
I think it may be related to setting the withRequestProcessingThreads, because it make the request to be processed in a different thread(rx-request-processor) instead of the nio-eventloop where the Threadlocal info is set. 

Do you think this is the case? Or am I using it wrong?

Thanks in advance!

**Comment by NiteshKant** [comment]
@jaume-pinyol you are correct that the reason for not finding the `requestId` is because you are using the `withRequestProcessingThreads()` option. 
If you are not using any blocking code as part of the processing of a request, you most likely do not require `withRequestProcessingThreads`.

**Comment by jaume-pinyol** [comment]
Thanks for the quick response! I think I've managed to fix my issue
