### ISSUE TITLE
Add HTTP 1.0 support

### ISSUE THREAD

**Issue by sdeleuze** [ReactiveX/RxNetty#575]
When benchmarking a Spring Web Reactive + RxNetty server application with a simple `ab -n 1 -c 1 http://localhost:8083/items/10` command, it blocks indefinitely while it works perfectly fine with `curl` or `wrk`. I think this is because `ab` is using HTTP 1.0 (we had the same issue on Reactor Netty). More details on https://jira.spring.io/browse/SPR-14964.

Could you confirm HTTP 1.0 is not supported yet?

**Comment by NiteshKant** [comment]
Use [HttpServer.sendHttp10ResponseFor10Request(true)](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-http/src/main/java/io/reactivex/netty/protocol/http/server/HttpServer.java#L304) to enable sending HTTP/1.0 responses for HTTP/1.0 requests. Javadoc of that method explains the reasoning behind this behavior.

**Comment by sdeleuze** [comment]
Ok thanks
