### ISSUE TITLE
How to adding IdleStateHandler in RxNetty?

### ISSUE THREAD

**Issue by probepark** [ReactiveX/RxNetty#577]
Hi guys.

I have a question that is simple.

I have tried to add client builder(used 0.4.x) with IdleStateHandler where pipelineConfigurator method, 
but that is not working.

I need a ping activity, I hope so.

Need a help!

**Comment by NiteshKant** [comment]
Can you explain what are you seeing that you categorize as "not working"?

0.4.x has `.readTimeout()` in `ClientConfig` if that helps.

**Comment by probepark** [comment]
@NiteshKant 
I know that readTimeout it can be useful.
but it only has read operation then, how can i get writeTimeout event? 
I think that idleStateHandler is ease to help generating writeTimeout event.
