### ISSUE TITLE
Content-length is set for GET request

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#58]
According to HTTP specification:

The presence of a message-body in a request is signaled by the inclusion of a Content-Length or Transfer-Encoding header field in the request's message-headers. A message-body MUST NOT be included in a request if the specification of the request method (section 5.1.1) does not allow sending an entity-body in requests.

But looks like in the last update "Content-length: 0" is automatically added for all requests without a content. This leads to Ribbon test failure when it talks to MockHttpServer which throws exception when seeing "Content-length" header on GET request.

**Comment by allenxwang** [comment]
The proposed fix is change in ClientRequestResponseConverter from

```
  if (!rxRequest.getHeaders().isContentLengthSet()) {
                    rxRequest.getHeaders().set(HttpHeaders.Names.CONTENT_LENGTH, 0);
                }
```

to

```
  if (!rxRequest.getHeaders().isContentLengthSet() && rxRequest.getMethod() != HttpMethod.GET) {
                    rxRequest.getHeaders().set(HttpHeaders.Names.CONTENT_LENGTH, 0);
                }
```

**Comment by NiteshKant** [comment]
@allenxwang your recent code changes, fixes this, rite?

**Comment by allenxwang** [comment]
Correct.
