### ISSUE TITLE
Different handlers for different URLs in RxNetty without strings compare

### ISSUE THREAD

**Issue by RostislavDugin** [ReactiveX/RxNetty#584]
I start use *RxNetty* and, at once, collided with problem: for each URL path must be different handler, but I didn't found simple and grateful decision. 

In example, URL `127.0.0.1:8080/some_request` must has handler `SomeRequestHandler`, but, at the same time, URL `127.0.0.1:8080/simple_request` must has `SimpleRequestHandler`.

----------

To solve my problem, I found this decisions:

   1. Simple strings comparing by parsing URLs. This decision include more boilerplate code and it is uncomfortable.
   2. Paths annotation (http://blog.cask.co/2015/12/introducing-netty-http-from-cask/) This is very good decision, but it work only with default *Netty* (without *Rx*) and required unofficial library `netty-http`, so future support can be doubt.

----------

So, how I can switch URLs paths for different handlers, but without boilerplate code (like as string comparing)? Maybe exists something like paths annotation, but for *RxNetty*?

----------

Equal answer on enSO: http://stackoverflow.com/questions/43837200/different-handlers-for-different-urls-in-rxnetty-without-strings-compare

**Comment by jamesgorman2** [comment]
Hi Rostislav,

you can look at https://github.com/pk11/rxnetty-router for 0.4.x or  https://github.com/Trunkplatform/rxnetty-router for 0.5.x 

The Trunkplatform version needs a custom maven source to get it in

James
