### ISSUE TITLE
RxNetty 0.5.2 stable?

### ISSUE THREAD

**Issue by moderakh** [ReactiveX/RxNetty#600]
Hi,

Thanks for the work on the project.
Your 0.5.2 release is not a beta release anymore. I wonder if that's stable for prod? and I wonder if you have stats on who is using it?

The wiki page says 0.5.x is not prod stable but I remember these notes where from the time when 0.5.x was a beta release. So are these notes still accurate?

Could you please respond to this?
Thanks.

**Comment by jamesgorman2** [comment]
Hi Mohammad,

* we have been running 0.5.x in production for 18 months without trouble
* no stats on who is using it
* I've been looking at a 1.0 release using RxJava2. This is currently at the API design stage (this is where most of the changes need to be). I have sketches but I want to make them clearer before putting out an RFC on them and have held up with other commitments. RxJava1 is in sunset so I need to do this in the next month. 

Given this, I'd 0.5 is stable w.r.t. itself, but a 1.0 release may contain significant API changes depending on the outcome of the RFC.

I realise this doesn't directly answer all your questions, but hopefully gives a clearer picture of where things are. If it doesn't please keep asking questions.

James

**Comment by moderakh** [comment]
@jamesgorman2 

Thanks for your quick response. We are taking a dependency on rxnetty:
https://mvnrepository.com/artifact/com.microsoft.azure/azure-documentdb-rx/0.9.0-rc2

Right now one big concern is there is not much activity on rxnetty project. If 0.5.2 is stable enough, I think it would be better if you could update the main rxnetty page and possibly remove that comment about 0.5.x not being a stable release.

Thanks for the good work and open sourcing rxnetty.

Thanks

**Comment by jamesgorman2** [comment]
Thanks for the feedback Mohammad. I'll update the readme/wiki with up to date info.

(and also most of the thanks should to @NiteshKant for his work over the years)

James

**Comment by jamesgorman2** [comment]
Updated in:

https://github.com/ReactiveX/RxNetty/commit/cdf30e46c0d81a2a35f395647c287f8df04ed4d6
https://github.com/ReactiveX/RxNetty/wiki/0.5.x-FAQs/53b392cd83ed7d882d91a29ef1d456c21b3885fd
