### ISSUE TITLE
Rename HttpRequest/HttpResponse with server/client perspective

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#63]
When doing server side programming with RxNetty which also uses its client to talk to other services, the server side HttpRequest/Response are mangled with client's corresponding objects that have the same name, which ends up having to use fully qualified name.

**Comment by allenxwang** [comment]
How about the following set

```
HttpServerRequest
HttpServerResponse
HttpClientRequest
HttpClientResponse
```

**Comment by benjchristensen** [comment]
Works for me.
