### ISSUE TITLE
HttpObjectAggregator is not in the correct position in the client pipeline

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#72]
`PipelineConfigurator.httpClientConfigurator()` returns a PipelineConfigurator that includes HttpObjectAggregator. However, it seems that this is never used as `ClientRequestResponseConverter` does not pass the HttpContent object to the next  handler in the pipeline.

It is not clear what the intention is. Are we still going to support out-of-the-box pipeline configuration that supports aggregated http response?

**Comment by NiteshKant** [comment]
ClientRequestResponseConverter is always added at the end of the pipeline (in this case after the aggregator) so it does not need to pass anything to the next handler. This is the handler that bridges netty's pipeline to Rx observers.

> > > Are we still going to support out-of-the-box pipeline configuration that supports aggregated http response?

The default client/server created by RxNetty always gets aggregated responses/requests as in general users do not want to handle HTTP chunks. If someone is using HTTP chunking as a streaming protocol, they would not be using the default HTTP client. They can instead use a client created with a pipeline without the aggregator.

**Comment by allenxwang** [comment]
Looks like ClientRequestResponseConverter is not added after the aggregator, but before aggregator.

Here is the code from `HttpClientPipelineConfigurator`

``` java
    @Override
    public void configureNewPipeline(ChannelPipeline pipeline) {
        pipeline.addLast(HTTP_CODEC_HANDLER_NAME,
                         new HttpClientCodec(maxInitialLineLength, maxHeaderSize, maxChunkSize, failOnMissingResponse,
                                             validateHeaders));
        pipeline.addLast(REQUEST_RESPONSE_CONVERTER_HANDLER_NAME, new ClientRequestResponseConverter());
    }
```

And in `PipelineConfigurators`

``` java
    public static <I, O> PipelineConfigurator<HttpClientResponse<O>, HttpClientRequest<I>> httpClientConfigurator() {
        return new PipelineConfiguratorComposite<HttpClientResponse<O>, HttpClientRequest<I>>(new HttpClientPipelineConfigurator<I, O>(),
                                                                                  new HttpObjectAggregationConfigurator());
    }
```

In `HttpObjectAggregationConfigurator`

``` java
    @Override
    public void configureNewPipeline(ChannelPipeline pipeline) {
        pipeline.addLast(AGGREGATOR_HANDLER_NAME, new HttpObjectAggregator(maxChunkSize));
    }
```

So the actual order of handlers in the pipeline is:

```
DefaultChannelPipeline{(http-client-codec = io.netty.handler.codec.http.HttpClientCodec), (request-response-converter = io.reactivex.netty.protocol.http.client.ClientRequestResponseConverter), (http-aggregator = io.netty.handler.codec.http.HttpObjectAggregator), (conn_lifecycle_handler = io.reactivex.netty.pipeline.ConnectionLifecycleHandler), (netty_observable_adapter = io.reactivex.netty.pipeline.ObservableAdapter)}
```

**Comment by allenxwang** [comment]
Looks like `HttpObjectAggregationConfigurator` should be updated to account for pipeline configuration differences between server vs. client. Here is the proposed fix:

``` java
    @Override
    public void configureNewPipeline(ChannelPipeline pipeline) {
        if (pipeline.get(HttpClientPipelineConfigurator.HTTP_CODEC_HANDLER_NAME) != null) {
            pipeline.addAfter(HttpClientPipelineConfigurator.HTTP_CODEC_HANDLER_NAME, AGGREGATOR_HANDLER_NAME, new HttpObjectAggregator(maxChunkSize));
        } else {
            pipeline.addLast(AGGREGATOR_HANDLER_NAME, new HttpObjectAggregator(maxChunkSize));
        }
    }
```

**Comment by NiteshKant** [comment]
> > > Looks like ClientRequestResponseConverter is not added after the aggregator, but before aggregator.

By design, it should only be added here: https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/protocol/http/client/ClientRequiredConfigurator.java#L34

The code to add it in HttpClientPipelineConfigurator seems like a bug, we can remove that code & it should work as expected. @allenxwang can you try this?

**Comment by allenxwang** [comment]
Yes, removing it from the HttpClientPipelineConfigurator fixed the issue. Will send a pull request.
