### ISSUE TITLE
Channel pool should listen for channel close events

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#76]
Currently the channel pool implementation does not have a way to react to close of underlying socket. It would depend on the next reuse of the connection or a background thread to detect such socket closures.
A scenario in which this limitation is highlighted is a ReadTimeoutHandler closing the connection after firing the timeout exception. In this case, the underlying connection will be in the idle pool till it is picked for reuse and a close is detected.

**Comment by allenxwang** [comment]
If we put the channel back to the idle pool without closing it, the next time it is picked for reuse and the read timeout has not happened yet, it will cause problem as we are sending another request on the channel without getting the response from the first request, right? Does HTTP protocol allow sending two requests on the same socket without getting the response from the first?

**Comment by allenxwang** [comment]
ConnectionLifecycleHandler remains in the pipeline after a channel is returned to the pool. Currently the channelUnregistered() method in this handler calls connection.close() which returns the channel to the pool. The pool will remove the channel if it is already closed and not reusable.

 Is channelUnregsitered() automatically called when channel is closed? If not, we just need to make connection.close() is called when channel is closed. Perhaps by overriding channelInactive()?

**Comment by NiteshKant** [comment]
> > > If we put the channel back to the idle pool without closing it

May be I was not clear in my description. I did not mean to put the channel back into the reusable pool before it is closed. I meant that; this is what will happen, if we close the connection after the request processing is over i.e. when readtimeout occurs. This was just an example. The basic problem is that we are not listening to socket close events, which can happen without user interaction, eg: Channel closed by the server.

> > > ConnectionLifecycleHandler remains in the pipeline after a channel is returned to the pool. Currently the channelUnregistered() method in this handler calls connection.close() which returns the channel to the pool. The pool will remove the channel if it is already closed and not reusable.

In the case when we close the connection (fix for issue #21 ) after we are done, conn.close() in channelUnregistered() will be a no-op as ObservableConnection ignore multiple close on the same connection. So, this call will not do what you expect it to do i.e. have isReusable() return false in the pool implementation.

> > > Is channelUnregsitered() automatically called when channel is closed?

Channel unregistered is called when the channel is unregistered from the eventloop which happens after channelInactive() is invoked i.e. when the channel is closed.

> > > If not, we just need to make connection.close() is called when channel is closed. Perhaps by overriding channelInactive()?

We need to explicitly remove this channel from the pool when we get a channelInactive() event as connection.close() may have been called before and hence will be ignored as explained above.

**Comment by NiteshKant** [comment]
Pull Request #95 fixes this issue. Since, now the Pool is an ObservableConnection pool, the connection.close() already invoked on the underlying connection close returns the connection to the pool, which discards the connection as it is not active.
