### ISSUE TITLE
AbstractQueueBasedChannelPool close idle connection from another route on pool exhaustion

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#79]
May be I am out of context here, so correct me if I am mistaken.

AbstractQueueBasedChannelPool has this code:
https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/client/pool/AbstractQueueBasedChannelPool.java#L172

which seems to suggest that if a connection is not available for a server, it will take it from another server. 
On the face of it, this seems to be misleading to say the least as the caller of requestChannel() expects to get the channel from the server it is requesting the connection from.

**Comment by allenxwang** [comment]
The comment may be a little misleading. It means getting the "quota" of the channel by closing an idle channel for another route. The channel that is finally returned is for the specified route as the new channel is created in the line 

https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/client/pool/AbstractQueueBasedChannelPool.java#L178

**Comment by NiteshKant** [comment]
> > > It means getting the "quota" of the channel by closing an idle channel for another route.

I see. IMHO, this is not really required and will create unnecessary connection churns. Your assumption seems to be that at this point there may be some other server which is less loaded and hence can sacrifice an idle connection. However, this will create unnecessary contention if all the underlying servers are relatively busy and have very less idle connections. I think we should leave this kind of resource utilization algorithms to the load balancer using these clients.

**Comment by allenxwang** [comment]
With load balancer, this kind of problem is less likely to occur since we can control which server to choose. However, the pool should also be able to use by one or more RxClient that does not use load balancer, or load balancer that only does simple round robin. In this case, I feel removing idle connection to accommodate connection request is better than fail.

Also, as @mhawthorne mentioned in #20, servers may be OUT OF SERVICE but having the persisted connections open. It is desirable to clean up such idle connections from client side.

**Comment by NiteshKant** [comment]
> > > With load balancer, this kind of problem is less likely to occur since we can control which server to choose.
> > > I mentioned load balancer to suggest that these resource optimizations i.e. finding which server has an idle connection that can be taken/closed, can be done better at the load balancer level since it has more insights into load per server. Just to be precise, this essentially will mean shifting load to the less utilized server and not directly reducing the idle pool.
> > > 
> > > I feel removing idle connection to accommodate connection request is better than fail.

The current random choosing of an idle connection is not helping. Instead, it may create issues if we start closing idle connections from the server that is in use. FWIW, the connection that is idle may just be created to process a request or in reaction to a load analysis strategy.
The important point here is that the decision to take an idle connection from another server can not be aptly done at this level. It can be very effectively done (as mentioned above) at the load balancer level.

> > > Also, as @mhawthorne mentioned in #20, servers may be OUT OF SERVICE but having the persisted connections open. It is desirable to clean up such idle connections from client side.

How is taking a random connection from any server helping this cause? RxClient will never be cognizant of OOS status as it never has insight into eureka. The only thing it can do is to randomly choose a connection or do naive decisions based as LRU.

**Comment by mhawthorne** [comment]
@NiteshKant I wouldn't call LRU naive in this case, but I see your point.

I think there are 2 issues here:

1) for the general open-source use case (not necessarily including Netflix's operational usage patterns), does it make sense to include client side connection cleanup?

2) Since we at Netflix do have use cases for killing connections (servers going out of service, server requests failing and having circuits tripped), should RxNetty expose the ability to find and kill connections for specific servers in a thread-safe way?  By safe I mean draining connections instead of killing them in mid-request.

The load balancing layer above RxNetty would know about the specific servers whose corresponding connections we want to kill, so if such an API was exposed we could solve the problem there.

**Comment by NiteshKant** [comment]
@mhawthorne so that we are on the same page, this particular discussion is around the piece of code which attempts to borrow quota (max total connections for a server farm) from other server when the quota has exhausted. This is done by randomly choosing an idle connection from any server in the farm and closing it. The need for this behavior is being discussed in this thread.

Most definitely, we need connection cleanup and we are doing it now, when we borrow a connection and it is no longer valid. In the near future @allenxwang will add a cleanup thread to clean such connections.

I termed LRU as naive in the context of load shedding i.e. choosing which server can sacrifice an idle connection. I called it naive as compared to a load-balancers ability to perform the same operation of load shedding in favor of a less loaded server by moving traffic to the less loaded server.

**Comment by allenxwang** [comment]
@mhawthorne @NiteshKant To optimize the connection pool usage with minimal connection churns, I am proposing the following:
- Provide an API to query/delete idle connections for a given host/port. Ribbon client can invoke this API when it sees a server is no longer available in Discovery.
- Periodically clean up idle connections in a thread if they have been idle for a configurable amount of time. This is the same as `connIdleEvictTimeMilliSeconds` currently configured for Ribbon RestClient, and can be shorter than the maximal idle time configured for the pool. 
- When a connection is requested, apply the same `connIdleEvictTimeMilliSeconds` as a criteria to remove idle connections from other routes if there is no more permit to create new connection. The pro is that we may have less connection request failures. The con is that it adds overhead to connection request and fail-fast may be better choice. Until we have a better insight in testing, we can make this optional and turn it on by default.

**Comment by NiteshKant** [comment]
I had a discussion in person with @allenxwang and we came to a conclusion that the subtle idle connection eviction between connection pool can 
- Skew the decisions/metrics made at a top level by ribbon load balancers.
- May create unnecessary connections churns

and hence is better left to the load balancer. 
In the case, a server is overloaded (connections exhausted) the load balancer should use a different server to send requests to. A sophisticated load balancer (non round-robin) will take this as input for further routing decisions.

Thus, pull request #95 removes this behavior.
