### ISSUE TITLE
Synchronized methods in AbstractQueueBasedChannelPool

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#83]
This could lead to hot locks specially if executed within a completely async application and gets executed in an eventloop.

For the methods in question, 

1) getTotalChannelsInPool() can just be a best effort and hence can remove synchronization. 
2) setMaxTotal() uses a semaphore underneath so does not need to be synchronized, rite?

**Comment by allenxwang** [comment]
getTotalChannelsInPool() is only used for monitoring purpose which should happen infrequently in background thread. I cannot imagine why it would be used for a normal connection request. 

I also expect that set should be called very rarely, possibly several times a day, and in a background thread.

If get and set is not synchronized and set is in process, getTotalChannelsInPool() may return an incorrect number which could be a dramatic surge or drop that exceeds the expected range. This might cause false alarm or confusion.

**Comment by allenxwang** [comment]
For set method, if two threads try to set the max at the same time and the method is not synchronized, maxTotal and maxConnectionsLimit may get out of sync. This will cause the get method return the wrong value for extended period of time until the next set.

**Comment by NiteshKant** [comment]
> > > For set method, if two threads try to set the max at the same time and the method is not synchronized, maxTotal and maxConnectionsLimit may get out of sync. This will cause the get method return the wrong value for extended period of time until the next set.

Since, AdjustableSemaphore is defined by us, the instance variable AbstractQueueBasedChannelPool.maxTotal seems redundant to me, as you can provide a getter in AdjustableSemaphore to get this value. Positive is that you don't have to worry about consistency between these values.

> > > getTotalChannelsInPool() is only used for monitoring purpose which should happen infrequently in background thread. I cannot imagine why it would be used for a normal connection request.
> > > I also expect that set should be called very rarely, possibly several times a day, and in a background thread.

It is a public method, we should not make assumptions about its usage.

> > > If get and set is not synchronized and set is in process, getTotalChannelsInPool() may return an incorrect number which could be a dramatic surge or drop that exceeds the expected range.

I think the question here is what are the repercussions of an incorrect value in the scenario when these calls are interleaved. Yes, it may give an incorrect value without synchronization but how big is that con as opposed to having locks in a publicly exposed methods. If we have alarms ringing for one instance of an incorrect value (which is fixed in the next call to the method), we have a different problem to solve.

I leave the decision to you, to me it does not seem necessary.

**Comment by NiteshKant** [comment]
After changes in pull request #95, we no more need these synchronized methods.
