### ISSUE TITLE
Add logging framework

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#85]
We don't have any logging in rx-netty module now. I think we need some logging when the code reaches production to help debugging. For example, we have debugged and found issues in Apache HttpClient connection pool when DEBUG logging is turned on.

**Comment by benjchristensen** [comment]
If we're doing this it should only be SL4J.

**Comment by NiteshKant** [comment]
As part of pull request #95 I have added SLF4J as a dependency to rx-netty. Closing this issue.
