### ISSUE TITLE
Default Client and Server Should Use Same Netty EventLoops

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxNetty#89]
Right now we create different event loops for both client and server. They should reuse the same as it is more efficient and right for most use cases.

**Comment by benjchristensen** [comment]
Here is how it defaults right now:

```
Daemon Thread [rx-server-selector-1-1] (Running)    
Daemon Thread [rx-server-selector-1-2] (Running)    
Daemon Thread [rx-client-selector-3-1] (Running)    
Daemon Thread [rx-client-selector-4-1] (Running)    
```

There should not be "client" and "server" selectors, just "rx-netty-selector" threads, sized to the number of cores on the machine.

**Comment by NiteshKant** [comment]
Created a pull request #92 for this. It will also fix the other issue where every RxClient instance was creating a new eventloop group.

**Comment by benjchristensen** [comment]
Thank you!
