### ISSUE TITLE
RxClient.DEFAULT_CONFIG may be muted

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#93]
If people use this code 

```
    ClientConfig config = new Builder(DEFAULT_CONFIG).build();
    config.readTimeout(...);
```

It ends up that the DEFAULT_CONFIG is muted for the read timeout. 

We probably should just copy the attributes instead of holding the reference of the passed in config in this constructor.

HttpClientConfig has the same problem.

**Comment by NiteshKant** [comment]
Yeah. I think we should remove the constant DEFAULT_CONFIG and replace it with a newDefaultConfig() method in these classes.

**Comment by NiteshKant** [comment]
In pull request #95 I have removed the DEFAULT_CONFIG constant and given no-arg constructors on the builders.
One can invoke Builder.newDefaultConfig() to get the default config.
